packages:
  - apps/*
  - packages/*

allowBuilds:
  '@serialport/bindings-cpp': true
  bufferutil: false
  core-js: true
  es5-ext: false
  esbuild: true
  node-red-contrib-bacnet: true
  onnxruntime-node: true
  oracledb: true
  utf-8-validate: false

patchedDependencies:
  three@0.185.1: patches/three@0.185.1.patch
