import * as THREE from "three";

interface ExportedMesh {
  name: string;
  vertices: number[];
  normals: number[];
  uvs: number[];
  color: THREE.Color;
  opacity: number;
}

function fbxName(value: string): string {
  return value.replace(/["\r\n]/g, "_").slice(0, 180) || "Mesh";
}

function numbers(values: number[]): string {
  return values.map((value) => Number.isFinite(value) ? Number(value.toFixed(7)) : 0).join(",");
}

function extractMeshes(root: THREE.Object3D): ExportedMesh[] {
  root.updateMatrixWorld(true);
  const meshes: ExportedMesh[] = [];
  root.traverse((object) => {
    if (!(object instanceof THREE.Mesh) || !isVisibleThroughRoot(object, root)) return;
    const sourcePosition = object.geometry.getAttribute("position");
    if (!sourcePosition || sourcePosition.count < 3) return;
    const geometry = object.geometry.index ? object.geometry.toNonIndexed() : object.geometry;
    const position = geometry.getAttribute("position");
    const normal = geometry.getAttribute("normal");
    const uv = geometry.getAttribute("uv");
    const normalMatrix = new THREE.Matrix3().getNormalMatrix(object.matrixWorld);
    const vertices: number[] = [];
    const normals: number[] = [];
    const uvs: number[] = [];
    const point = new THREE.Vector3();
    const direction = new THREE.Vector3();
    for (let index = 0; index < position.count; index += 1) {
      point.fromBufferAttribute(position, index).applyMatrix4(object.matrixWorld);
      vertices.push(point.x, point.y, point.z);
      if (normal) {
        direction.fromBufferAttribute(normal, index).applyMatrix3(normalMatrix).normalize();
        normals.push(direction.x, direction.y, direction.z);
      }
      if (uv) uvs.push(uv.getX(index), uv.getY(index));
    }
    const material = (Array.isArray(object.material) ? object.material[0] : object.material) as THREE.Material & { color?: THREE.Color; opacity?: number };
    meshes.push({
      name: fbxName(object.name || `Mesh ${meshes.length + 1}`),
      vertices,
      normals,
      uvs,
      color: material?.color?.clone() ?? new THREE.Color(0xbcc3c7),
      opacity: material?.transparent ? Math.max(0, Math.min(1, material.opacity ?? 1)) : 1
    });
    if (geometry !== object.geometry) geometry.dispose();
  });
  return meshes;
}

function isVisibleThroughRoot(object: THREE.Object3D, root: THREE.Object3D): boolean {
  let current: THREE.Object3D | null = object;
  while (current) {
    if (!current.visible) return false;
    if (current === root) return true;
    current = current.parent;
  }
  return false;
}

/** Exports visible static meshes as Autodesk-compatible ASCII FBX 7.4. */
export function exportFbxAscii(root: THREE.Object3D): string {
  const meshes = extractMeshes(root);
  if (meshes.length === 0) throw new Error("当前场景没有可导出的可见网格");
  const lines: string[] = [
    ";".repeat(220),
    "; FBX 7.4.0 project file",
    "; Generated by DeepMonkey Studio",
    "FBXHeaderExtension:  {",
    "\tFBXHeaderVersion: 1003",
    "\tFBXVersion: 7400",
    '\tCreator: "DeepMonkey Studio"',
    "}",
    "GlobalSettings:  {",
    "\tVersion: 1000",
    "\tProperties70:  {",
    '\t\tP: "UpAxis", "int", "Integer", "",1',
    '\t\tP: "UpAxisSign", "int", "Integer", "",1',
    '\t\tP: "FrontAxis", "int", "Integer", "",2',
    '\t\tP: "FrontAxisSign", "int", "Integer", "",-1',
    '\t\tP: "CoordAxis", "int", "Integer", "",0',
    '\t\tP: "CoordAxisSign", "int", "Integer", "",1',
    '\t\tP: "UnitScaleFactor", "double", "Number", "",100',
    "\t}",
    "}",
    "Definitions:  {",
    "\tVersion: 100",
    `\tCount: ${meshes.length * 3}`,
    '\tObjectType: "Geometry" {',
    `\t\tCount: ${meshes.length}`,
    "\t}",
    '\tObjectType: "Model" {',
    `\t\tCount: ${meshes.length}`,
    "\t}",
    '\tObjectType: "Material" {',
    `\t\tCount: ${meshes.length}`,
    "\t}",
    "}",
    "Objects:  {"
  ];
  const connections: string[] = [];
  meshes.forEach((mesh, meshIndex) => {
    const geometryId = 100_000 + meshIndex * 10;
    const modelId = geometryId + 1;
    const materialId = geometryId + 2;
    const vertexCount = mesh.vertices.length / 3;
    const polygonIndices: number[] = [];
    for (let vertex = 0; vertex + 2 < vertexCount; vertex += 3) polygonIndices.push(vertex, vertex + 1, -(vertex + 3));
    lines.push(
      `\tGeometry: ${geometryId}, "Geometry::${mesh.name}", "Mesh" {`,
      "\t\tGeometryVersion: 124",
      `\t\tVertices: *${mesh.vertices.length} {`,
      `\t\t\ta: ${numbers(mesh.vertices)}`,
      "\t\t}",
      `\t\tPolygonVertexIndex: *${polygonIndices.length} {`,
      `\t\t\ta: ${polygonIndices.join(",")}`,
      "\t\t}"
    );
    if (mesh.normals.length === mesh.vertices.length) lines.push(
      "\t\tLayerElementNormal: 0 {",
      "\t\t\tVersion: 101",
      '\t\t\tName: ""',
      '\t\t\tMappingInformationType: "ByPolygonVertex"',
      '\t\t\tReferenceInformationType: "Direct"',
      `\t\t\tNormals: *${mesh.normals.length} {`,
      `\t\t\t\ta: ${numbers(mesh.normals)}`,
      "\t\t\t}",
      "\t\t}"
    );
    if (mesh.uvs.length === vertexCount * 2) lines.push(
      "\t\tLayerElementUV: 0 {",
      "\t\t\tVersion: 101",
      '\t\t\tName: "UVChannel_1"',
      '\t\t\tMappingInformationType: "ByPolygonVertex"',
      '\t\t\tReferenceInformationType: "Direct"',
      `\t\t\tUV: *${mesh.uvs.length} {`,
      `\t\t\t\ta: ${numbers(mesh.uvs)}`,
      "\t\t\t}",
      "\t\t}"
    );
    lines.push(
      "\t\tLayerElementMaterial: 0 {",
      "\t\t\tVersion: 101",
      '\t\t\tMappingInformationType: "AllSame"',
      '\t\t\tReferenceInformationType: "IndexToDirect"',
      "\t\t\tMaterials: *1 {",
      "\t\t\t\ta: 0",
      "\t\t\t}",
      "\t\t}",
      "\t\tLayer: 0 {",
      "\t\t\tVersion: 100",
      ...(mesh.normals.length ? ["\t\t\tLayerElement:  {", '\t\t\t\tType: "LayerElementNormal"', "\t\t\t\tTypedIndex: 0", "\t\t\t}"] : []),
      ...(mesh.uvs.length ? ["\t\t\tLayerElement:  {", '\t\t\t\tType: "LayerElementUV"', "\t\t\t\tTypedIndex: 0", "\t\t\t}"] : []),
      "\t\t\tLayerElement:  {",
      '\t\t\t\tType: "LayerElementMaterial"',
      "\t\t\t\tTypedIndex: 0",
      "\t\t\t}",
      "\t\t}",
      "\t}",
      `\tModel: ${modelId}, "Model::${mesh.name}", "Mesh" {`,
      "\t\tVersion: 232",
      "\t\tProperties70:  {",
      '\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",0,0,0',
      '\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0',
      '\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1',
      "\t\t}",
      "\t}",
      `\tMaterial: ${materialId}, "Material::${mesh.name}", "" {`,
      "\t\tVersion: 102",
      '\t\tShadingModel: "phong"',
      "\t\tMultiLayer: 0",
      "\t\tProperties70:  {",
      `\t\t\tP: "DiffuseColor", "Color", "", "A",${numbers([mesh.color.r, mesh.color.g, mesh.color.b])}`,
      `\t\t\tP: "TransparencyFactor", "Number", "", "A",${Number((1 - mesh.opacity).toFixed(5))}`,
      "\t\t}",
      "\t}"
    );
    connections.push(`\tC: "OO",${geometryId},${modelId}`, `\tC: "OO",${materialId},${modelId}`, `\tC: "OO",${modelId},0`);
  });
  lines.push("}", "Connections:  {", ...connections, "}");
  return `${lines.join("\n")}\n`;
}
