/**
 * OpenUSD 官方仓库的最小离线验收样本。仅用于加载器回归，避免 CI 依赖网络。
 * 来源与 SHA-256 记录在 docs/openusd-asset-pipeline.md。
 */
export const OFFICIAL_SPHERE_USDA = '#usda 1.0\n\ndef Sphere "sphere"\n{\n}\n';

export const OFFICIAL_SKINNED_ARM_USDA = `#usda 1.0
(
    defaultPrim = "Model"
    endTimeCode = 10
    startTimeCode = 1
    metersPerUnit = .01
    upAxis = 'Y'
)

def SkelRoot "Model" (
    kind = "component"
    prepend apiSchemas = ["SkelBindingAPI"]
)
{
    def Skeleton "Skel" (
        prepend apiSchemas = ["SkelBindingAPI"]
    )
    {
        uniform token[] joints = ["Shoulder", "Shoulder/Elbow", "Shoulder/Elbow/Hand"]
        uniform matrix4d[] bindTransforms = [
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1)),
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,2,1)),
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,2,1))
        ]
        uniform matrix4d[] restTransforms = [
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1)),
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,2,1)),
            ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,2,1))
        ]
        def SkelAnimation "Anim" {
            uniform token[] joints = ["Shoulder/Elbow"]
            float3[] translations = [(0,0,2)]
            quatf[] rotations.timeSamples = {
                1: [(1,0,0,0)],
                10: [(0.7071, 0.7071, 0, 0)]
            }
            half3[] scales = [(1,1,1)]
        }
        rel skel:animationSource = </Model/Skel/Anim>
    }
    def Mesh "Arm" (
        prepend apiSchemas = ["SkelBindingAPI"]
    )
    {
       int[] faceVertexCounts = [4,4,4,4,4,4,4,4,4,4]
       int[] faceVertexIndices = [
           2,3,1,0, 6,7,5,4, 8,9,7,6, 3,2,9,8, 10,11,4,5,
           0,1,11,10, 7,9,10,5, 9,2,0,10, 3,8,11,1, 8,6,4,11
       ]
       point3f[] points = [
           (0.5,-0.5,4),(-0.5,-0.5,4),(0.5,0.5,4),(-0.5,0.5,4),
           (-0.5,-0.5,0),(0.5,-0.5,0),(-0.5,0.5,0),(0.5,0.5,0),
           (-0.5,0.5,2),(0.5,0.5,2),(0.5,-0.5,2),(-0.5,-0.5,2)
       ]
       rel skel:skeleton = </Model/Skel>
       int[] primvars:skel:jointIndices = [2,2,2,2,0,0,0,0,1,1,1,1] (
           interpolation = "vertex"
           elementSize = 1
       )
       float[] primvars:skel:jointWeights = [1,1,1,1,1,1,1,1,1,1,1,1] (
           interpolation = "vertex"
           elementSize = 1
       )
       matrix4d primvars:skel:geomBindTransform = ((1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1))
    }
}
`;

export const OFFICIAL_GEOM_USDC_BASE64 = [
  "UFhSLVVTREMACAAAAAAAACcEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAACABAAAAAAAAAAUAAAABAAAAAAAAAAcAAAABAAAAAAAAAAgAAAAgAQAAAAAA",
  "AAAKAAAACQAAAAAAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAARAAAAEgAAABMAAAABAAAAAAAAABQAAAABAAAAAAAAABwA",
  "AAABAAAAAAAAAB0AAAADAQAAAAAAAAAJAAAAAwEAAAAAAAAADgAAAAMCAAAAAAAAABAAAAAOAAAAJgAAAAAAAACnAQAAAAAA",
  "ADgBAAAAAAAAAPM3Oy0pAFdvcmxkAHByaW1DaGlsZHJlbgAAc3BlY2lmaWVyAE1hdGVyaWFsQmluZGluZ0FQSQBhcGlTY2hl",
  "bWFzAGdlb20AbSMAIjpiJAD1GTpjb2xsZWN0aW9uOnByZXZpZXc6c3Vic2V0cwBwcm9wZXJ0aWVzAEMmADNBUEkhAAAUAPUw",
  "AG1lc2gAc3BoZXJlAGN5bGluZGVyAGNvbmUAcG9pbnRzAGJhc2lzQ3VydmVzAGNhcHN1bGUAY3ViZQBudXJiGQAFXwAHXAC3",
  "OmluY2x1ZGVzAEJEAKN0eXBlTmFtZQBDTQAQQ20AEENSABRDgAAQTZUAAO8AEVPKAA31ACYARxwAF06HABJQswASU88A9Qh2",
  "YXJpYWJpbGl0eQB0YXJnZXRQYXRoc04ADrYAUENvbGwAAAAAAAAAAAAZAAAAAAAAAB0AAAAAAAAAAPALAAAAAFVVBUAFFAAC",
  "AgL8B/sC/AcN7AcNDAGDAAAAAAAAAAAgWAABADApAAEHAEEAKkBkCAAxIABxCAAzKQB9CAABBwBBACpAiQkAMSAAlggAMykA",
  "wggAERUIADMLQBcIABMYCAATGQgAExoIABMbCAARzggAMykA2ggAER4IADMLQB8IABMgCAATIQgAAqAAMSxA5hAAMyIA8wgA",
  "gAABAAAAACIANgAAAAAAAAA/AAAAAAAAAADwLQYAAABVFVUUBVEUVVEURVVVBQD/AgEBAfsBAQH3BPYF9fQH8wjyCfQNAe8M",
  "7g3tDuwP6xYB6RYC6BYD5xIAAAAAAAAAEgAAAAAAAAAVAAAAAAAAAADwAwEAAABRFQAFBAAQ8Q799gf6AhwAAAAAAAAAAPAK",
  "/v///1FVFVUFA/cP1BEkAf0E+9g59/z9GBUAAAAAAAAAAPADAAAAAFEBQBUB/wEO8gP9/gL+EAAAAAAAAAANAAAAAAAAAACw",
  "AQAAAAEAAFAAAgIPAAAAAAAAAADQAwAAAFUABAAAAgUFBg0AAAAAAAAAALAAAAAABQAABAf/AgYAAAAAAAAAVE9LRU5TAAAA",
  "AAAAAAAAABEBAAAAAAAAUAEAAAAAAABTVFJJTkdTAAAAAAAAAAAAYQIAAAAAAAAIAAAAAAAAAEZJRUxEUwAAAAAAAAAAAABp",
  "AgAAAAAAALgAAAAAAAAARklFTERTRVRTAAAAAAAAACEDAAAAAAAATwAAAAAAAABQQVRIUwAAAAAAAAAAAAAAcAMAAAAAAABu",
  "AAAAAAAAAFNQRUNTAAAAAAAAAAAAAADeAwAAAAAAAEkAAAAAAAAA",
].join("");

export const OFFICIAL_SIMPLE_MESH_USDZ_BASE64 = [
  "UEsDBAoAAAAAAHgIU03CGzjZnAUAAJwFAAAPABMAc2ltcGxlTWVzaC51c2RjhhkPAAAAAAAAAAAAAAAAAAAAAFBYUi1VU0RD",
  "AAcAAAAAAADUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAABAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAIAAAAAAAAAAwAAAAAAAxAAQAAAAgAAAAAAAAAAgAAAAAACkABAAAA",
  "AAAAAA8AAAABAAAAAAAAABAAAAAGAAAAAAAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAAAAAAAACAAAAAAAAAAAAAL8AAAC/",
  "AAAAvwAAAD8AAAA/AAAAPwYAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAGAAAAAAAAAAaAAAAAAAAAADUAgAAAEVF",
  "RVVVBQAB/wMAgPr/AQb+/gP6AAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAACAPwAAAAAAAAAAAAAAAAAAgL8AAAAA",
  "AACAvwAAAAAAAIA/AAAAAAAAAAAAAIC/AAAAAAAAAAAIAAAAAAAAAAAAAL8AAAC/AAAAPwAAAD8AAAC/AAAAPwAAAL8AAAA/",
  "AAAAPwAAAD8AAAA/AAAAPwAAAL8AAAA/AAAAvwAAAD8AAAA/AAAAvwAAAL8AAAC/AAAAvwAAAD8AAAC/AAAAvyMAAAAAAAAA",
  "PgEAAAAAAAAhAQAAAAAAAADyTFkAdXBBeGlzAHNpbXBsZU1lc2gAcHJpbUNoaWxkcmVuAGRlZmF1bHRQcmltAABzcGVjaWZp",
  "ZXIAWGZvcm0AdHlwZU5hbWUAY29tcG9uZW50AGtpbmQAaWRlbnQpAAZYAPEQLnVzZGMAbmFtZQBhc3NldEluZm8AR2VvbQBj",
  "dWJlAHsA8CZzdWJkaXZpc2lvblNjaGVtZQBwb2ludHMAZXh0ZW50AG5vcm1hbHMAZmFjZVZlcnRleENvdSAABhEA9AxJbmRp",
  "Y2VzAHByb3BlcnRpZXMAZmxvYXQzW13NAGMAaW50W11NAIEzZltdAHVuadEA0mludGVycG9sYXRpb258AAEgAPAIdG9rZW4A",
  "dmFyaWFiaWxpdHkAbm9uZQADAAAAAAAAAAsAAAANAAAAAgAAABgAAAAAAAAAIQAAAAAAAAAA8A8CAAAAEVBVVVVVAQEE9QAF",
  "EPAS7hIA7hIE6hLuGfmKAAAAAAAAAAARAAEAMQtAWAgAMSkAAggAIQtABwBBACpABwkAMwtACQgAEWQIADEfAJQIADMpAKAI",
  "ABERCAAxC0CsCAAxKQAZCAAxC0DQCAAxGIAbCAAxC0DwCABAA4AQAQkAMAOgHAcAQQALQEAQADMYgB0QABMfCAATkBgAEyAQ",
  "AAEPALAALEAiAAAAAAALQCUAAAAAAAAAKAAAAAAAAAAA8BYBAAAAQQFUFUVRFRQFAQD9BPgEBfcEBvUM8w7xDgLwEe0U6xbo",
  "CgAAAAAAAAAKAAAAAAAAAAoAAAAAAAAAAIABAAAAAQAAABIAAAAAAAAAAPAAAQAAABVVAQX9Ddz+/wICDAAAAAAAAAAAoAAA",
  "AAABAQT/Af4KAAAAAAAAAAoAAAAAAAAAAIABAAAAAQAAAA4AAAAAAAAAAMADAAAAFQEBAAQGBAQMAAAAAAAAAACgAAAAAAUB",
  "AAf/+wYAAAAAAAAAVE9LRU5TAAAAAAAAAAAAAPgBAAAAAAAAOQEAAAAAAABTVFJJTkdTAAAAAAAAAAAAMQMAAAAAAAAUAAAA",
  "AAAAAEZJRUxEUwAAAAAAAAAAAABFAwAAAAAAAMMAAAAAAAAARklFTERTRVRTAAAAAAAAAAgEAAAAAAAAOAAAAAAAAABQQVRI",
  "UwAAAAAAAAAAAAAAQAQAAAAAAABQAAAAAAAAAFNQRUNTAAAAAAAAAAAAAACQBAAAAAAAAEQAAAAAAAAAUEsBAgAACgAAAAAA",
  "eAhTTcIbONmcBQAAnAUAAA8AEwAAAAAAAAAAAAAAAAAAAHNpbXBsZU1lc2gudXNkY4YZDwAAAAAAAAAAAAAAAAAAAABQSwUG",
  "AAAAAAEAAQBQAAAA3AUAAAAA",
].join("");
