// GENERATED by scripts/generate-frame-abi.mjs — 手改无效，改 schema 后重新生成。
// source: packages/deep-engine/frame-abi/frame-abi.schema.json
// schema-sha256: 3291dacc0f11c4520e41d95c006be16fb5192d31d2fe5cbd4e09bbe61f40e54c
//! J2-B7 单源 frame 布局（Rust 宿主 deep.native.frame.v8，596f/2384B）。
//! 常量带 FRAME_ABI_ 前缀与手写 mesh_abi 常量并存；parity 门见 frame_layout_gate.rs。

pub const FRAME_ABI_SCHEMA_SHA256: &str =
    "3291dacc0f11c4520e41d95c006be16fb5192d31d2fe5cbd4e09bbe61f40e54c";
pub const FRAME_ABI_TS_FLOATS: usize = 96;
pub const FRAME_ABI_TS_BYTES: u64 = 384;
pub const FRAME_ABI_RUST_FLOATS: usize = 596;
pub const FRAME_ABI_RUST_BYTES: u64 = 2384;
pub const FRAME_ABI_RUST_ROWS: usize = 149;

/// TS=pipelines.ts:16 currentViewProjection；Rust=mesh_abi.rs frame_uniform legacy[0..3]
pub const FRAME_ABI_VIEW_PROJECTION: usize = 0;

/// TS=lightViewProjection；Rust=legacy[4..7] light[0..3]
pub const FRAME_ABI_LIGHT_VIEW_PROJECTION: usize = 4;

/// TS=eye（C4 camera-relative 后为相机原点相关量）；Rust=legacy[8]
pub const FRAME_ABI_EYE: usize = 8;

/// legacy[9]=[0.012,0.020,0.035,1.0]、legacy[10]=[0,0,0,1]——演示口径遗留行，语义未与 TS 对齐，只记录不声明同义
pub const FRAME_ABI_LEGACY_SCENE_ROWS: usize = 9;

/// TS=lightDirection；Rust=legacy[11] 太阳方向
pub const FRAME_ABI_LIGHT_DIRECTION: usize = 11;

/// legacy[12]=[0;4] 全零保留行（mesh_abi.rs:119）
pub const FRAME_ABI_LEGACY_ZERO_ROW: usize = 12;

/// TS=sunColor；Rust=legacy[13]（w=0 旧包固定灯光标记，v2 作者灯光=2）
pub const FRAME_ABI_SUN_COLOR: usize = 13;

/// legacy[14]=[exposure, shadowEnabled, 0, 0]（mesh_abi.rs:121-122）
pub const FRAME_ABI_EXPOSURE_SHADOW_ENABLED: usize = 14;

/// 灯 i 起 15+i*4；第 4 行 18+i*4 为阴影记账：[2]=castShadow 槽位、[3]=near*far/(far-near)（scene_lighting.rs:67,80,87）
pub const FRAME_ABI_LOCAL_LIGHTS: usize = 15;

/// 16 阴影视图矩阵
pub const FRAME_ABI_LOCAL_SHADOW_VIEWS: usize = 79;

/// 雾投影（2288B 断言 mesh_abi.rs:209）；构造默认 [near,far,0,0]
pub const FRAME_ABI_FOG_PROJECTION_ROW: usize = 143;

/// 16 灯软度标量（2304B 断言 mesh_abi.rs:210）
pub const FRAME_ABI_LOCAL_SOFTNESS_ROW: usize = 144;

/// 雾剖面
pub const FRAME_ABI_FOG_PROFILE_ROW: usize = 148;
