pub mod asset_package;
pub mod behavior_ir;
pub mod bloom;
pub mod cascaded_shadow;
mod cascaded_shadow_math;
pub mod chart;
pub mod contract;
pub mod culling_contract;
pub mod dashboard_runtime;
pub mod deep2d;
pub mod executable_overlay;
pub mod fog;
pub mod half_decode;
pub mod host_capabilities;
pub mod ibl;
pub mod lod_contract;
pub mod mesh_abi;
pub mod native_ui;
pub mod pbr_brdf;
pub mod pbr_reference;
pub mod pbr_texture;
pub mod platform_text;
pub mod player_view;
pub mod runtime_camera;
pub mod runtime_coordinates;
pub mod runtime_package;
pub mod scene;
mod scene_alpha;
pub mod scene_bounds;
mod scene_pack;
pub mod scene_resource_domain;
pub mod scene_resource_identity;
pub mod shader_disk_cache;
pub mod shader_package;
pub mod shadow_cache;

pub const NATIVE_SHADER_VERSION: u32 = 1;
