<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BimStudio.RevitWorker</AssemblyName>
    <RootNamespace>BimStudio.RevitWorker</RootNamespace>
  </PropertyGroup>
</Project>
