import type { SceneSnapshot } from "@bim-studio/contracts";
import { api } from "./api";
import { isModelLoadSuperseded, waitForModelReady } from "./appModelLoading";
import { createApplicationRuntimeController } from "./controllers/applicationRuntimeController";
import { sortScenesByTime } from "./appSceneOrder";
import { createSceneEditorController } from "./controllers/sceneEditorController";
import { createScenePersistenceController } from "./controllers/scenePersistenceController";
import { useScenePublicationArtifacts } from "./hooks/useScenePublicationArtifacts";
import { useAppDerivedState } from "./hooks/useAppDerivedState";
import { useGlobalDialogEscape } from "./hooks/useGlobalDialogEscape";
import { useAppLifecycleEffects } from "./hooks/useAppLifecycleEffects";
import { useAppNavigationController } from "./hooks/useAppNavigationController";
import { useAppRuntimeEffects } from "./hooks/useAppRuntimeEffects";
import { useAppSceneSyncEffects } from "./hooks/useAppSceneSyncEffects";
import { useAppState } from "./hooks/useAppState";
import { useSceneHistoryActions } from "./hooks/useSceneHistoryActions";
import { useApplicationRecovery } from "./hooks/useApplicationRecovery";
import { useSceneHistoryState } from "./hooks/useSceneHistoryState";
import { useScenePlayMode } from "./hooks/useScenePlayMode";
import { createRestrictedPlayConsumer, type RestrictedPlayConsumer } from "./scripting/restrictedPlayConsumer";
import { useRef } from "react";
import { downloadWorkspaceRecoveryDraft } from "./studio/workspaceRecoveryStore";
import type { AppViewBindings } from "./views/appViewBindings";
import { AppRootView } from "./views/AppRootView";
import { NetworkStatusBanner } from "./appStatus/NetworkStatusBanner";

export function App() {
  const appState = useAppState();
  useGlobalDialogEscape();
  const {
    initialPathRef,
    defaultEntryAppliedRef,
    viewportRef,
    uploadRef,
    importRef,
    environmentMapRef,
    materialTextureRef,
    materialTextureKindRef,
    sceneNameCommitRef,
    sceneApplyVersionRef,
    sceneWorkspaceLoadRef,
    rendererSnapshotRef,
    rendererPreferenceCommitRef,
    webGpuSceneReplacementCountRef,
    applicationSessionRef,
    activeSceneIdRef,
    pendingSceneFocusRef,
    visionEventCursorRef,
    behaviorManagerRef,
    behaviorCommandQueueRef,
    engine,
    setEngine,
    currentUser,
    setCurrentUser,
    branding,
    setBranding,
    authReady,
    setAuthReady,
    rendererBackend,
    setRendererBackend,
    rendererActiveBackend,
    setRendererActiveBackend,
    rendererSwitchPhase,
    setRendererSwitchPhase,
    rendererSwitchMessage,
    setRendererSwitchMessage,
    rendererSwitching,
    setRendererSwitching,
    rendererGeneration,
    setRendererGeneration,
    rendererDiagnosticsOpen,
    setRendererDiagnosticsOpen,
    systemInitialTab,
    setSystemInitialTab,
    studioPublishMode,
    setStudioPublishMode,
    studioPublishPerformance,
    setStudioPublishPerformance,
    studioPublishOpen,
    setStudioPublishOpen,
    studioCloudConfigured,
    setStudioCloudConfigured,
    studioCloudHint,
    setStudioCloudHint,
    projects,
    setProjects,
    project,
    setProject,
    scenes,
    setScenes,
    managerApplications,
    setManagerApplications,
    activeScene,
    setActiveScene,
    applicationRevision,
    setApplicationRevision,
    sceneName,
    setSceneName,
    selected,
    setSelected,
    measurements,
    setMeasurements,
    revision,
    setRevision,
    uploading,
    setUploading,
    rvtConversionMode,
    setRvtConversionMode,
    revitRuntime,
    setRevitRuntime,
    rvtRevitVersion,
    setRvtRevitVersion,
    busy,
    setBusy,
    viewerLoadState,
    setViewerLoadState,
    autoSaveEnabled,
    setAutoSaveEnabled,
    lastAutoSavedSceneRevisionRef,
    message,
    setMessage,
    error,
    setError,
    measureEnabled,
    setMeasureEnabled,
    annotationEnabled,
    setAnnotationEnabled,
    annotations,
    setAnnotations,
    selectedAnnotationId,
    setSelectedAnnotationId,
    selectedSpace,
    setSelectedSpace,
    transformMode,
    setTransformMode,
    selectionScope,
    setSelectionScope,
    navigationMode,
    setNavigationMode,
    navigationDiagnostics,
    setNavigationDiagnostics,
    measureMode,
    setMeasureMode,
    route,
    setRoute,
    dataReturnRouteRef,
    viewerRouteActive,
    applicationState,
    activeApplication,
    activeDashboardPage,
    activeTopology,
    topologyDataProducts,
    setTopologyDataProducts,
    topologyRuntimeStates,
    setTopologyRuntimeStates,
    avatarVisible,
    setAvatarVisible,
    cameraInfo,
    setCameraInfo,
    pointerInfo,
    setPointerInfo,
    infoEnabled,
    setInfoEnabled,
    frameRate,
    setFrameRate,
    weather,
    setWeather,
    environmentOpen,
    setEnvironmentOpen,
    lighting,
    setLighting,
    sceneEnvironment,
    setSceneEnvironment,
    sceneCoordinates,
    setSceneCoordinates,
    configuredDefaultEnvironment,
    postProcessing,
    setPostProcessing,
    physics,
    setPhysics,
    physicsOpen,
    setPhysicsOpen,
    engineeringAnalysis,
    setEngineeringAnalysis,
    selectedLightId,
    setSelectedLightId,
    creditsOpen,
    setCreditsOpen,
    digitalTwinOpen,
    setDigitalTwinOpen,
    sceneDataStatus,
    setSceneDataStatus,
    sceneDataReceived,
    setSceneDataReceived,
    aiAssistantOpen,
    setAiAssistantOpen,
    sceneDashboard,
    setSceneDashboard,
    sceneDataBindings,
    setSceneDataBindings,
    sceneAssetBindings,
    setSceneAssetBindings,
    sceneDataBindingRuntime,
    setSceneDataBindingRuntime,
    sceneInteractions,
    setSceneInteractions,
    viewerToolsOpen,
    setViewerToolsOpen,
    xrPanelOpen,
    setXrPanelOpen,
    xrActiveMode,
    setXrActiveMode,
    xrCapabilities,
    setXrCapabilities,
    locale,
    setLocale,
    sceneAnimation,
    setSceneAnimation,
    cameraViews,
    setCameraViews,
    cameraConstraints,
    setCameraConstraints,
    navigationSettings,
    setNavigationSettings,
    defaultCameraViewId,
    setDefaultCameraViewId,
    cameraViewsOpen,
    setCameraViewsOpen,
    animationTime,
    setAnimationTime,
    animationPlaying,
    setAnimationPlaying,
    animationOpen,
    setAnimationOpen,
    componentQuery,
    setComponentQuery,
    componentLevel,
    setComponentLevel,
    componentCategory,
    setComponentCategory,
    floorExpansionByModel,
    setFloorExpansionByModel,
    clipping,
    setClippingState,
    expandedModels,
    setExpandedModels,
    sceneOrganizationOpen,
    setSceneOrganizationOpen,
    sceneImportOpen,
    setSceneImportOpen,
    sceneBehaviorOpen,
    setSceneBehaviorOpen,
    sceneBehaviorActive,
    setSceneBehaviorActive,
    sceneBehaviorPaused,
    setSceneBehaviorPaused,
    sceneBehaviorEntries,
    setSceneBehaviorEntries,
    sceneBehaviorLogs,
    setSceneBehaviorLogs,
    inspectorTab,
    setInspectorTab,
    sceneOrganizationSelection,
    setSceneOrganizationSelection,
    selectionSets,
    setSelectionSets,
    rootLayerOrder,
    setRootLayerOrder,
    lastDeletedSelectionSet,
    setLastDeletedSelectionSet,
    projectDialogMode,
    setProjectDialogMode,
    newProjectName,
    setNewProjectName,
    newProjectDescription,
    setNewProjectDescription,
    primitiveColors,
    interactionTargetOptions,
    showError,
    rendererDiagnostics,
  } = appState;
  const restrictedPlayRef = useRef<RestrictedPlayConsumer | undefined>(undefined);
  const playMode = useScenePlayMode(() => ({
    engine,
    capture: () => sceneHistoryState.sceneSnapshotFactoryRef.current?.(),
    flush: () => sceneHistoryState.flushSceneHistoryEdit(),
    applyScene: async (snapshot) => {
      if (!project || engine?.getAuthorRendererBackend() === "webgpu") {
        throw new Error("当前渲染器无法安全地同步恢复播放快照，请切换 WebGL 后重试");
      }
      await applyScene(snapshot, false, project, false, false, false, true);
      if (!engine?.hasRestoredSceneSnapshot(snapshot.id)) throw new Error("场景恢复尚未完成，请待模型加载结束后重试退出播放");
    },
    readAnimationPlayhead: () => {
      try { return engine?.transientChannels.channel<{ time: number; playing: boolean }>("animation").snapshot().time ?? animationTime; }
      catch { return animationTime; }
    },
    reportError: showError,
  }));
  const sceneHistoryState = useSceneHistoryState({ activeScene, routeView: route.view, sceneBehaviorActive, animationPlaying, playModeActive: playMode.active });
  const {
    recoveryDraft,
    setRecoveryDraft,
    recoveryBusy,
    setRecoveryBusy,
    recoveryDecisionRef,
    sceneHistoryRef,
    sceneSnapshotFactoryRef,
    sceneHistoryApplyingRef,
    sceneHistoryRecordRef,
    sceneHistoryRevision,
    flushSceneHistoryEdit,
  } = sceneHistoryState;

  const {
    managerDirectory,
    navigate,
    openDataCenter,
    closeDataCenter,
    openDocs,
    closeDocs,
    replaceDashboardView,
    changeRendererBackend,
    switchProject,
    switchProjectById,
    openProjectDialog,
    submitProjectDialog,
    deleteCurrentProject,
    refreshProject,
  } = useAppNavigationController({ state: appState, sceneSnapshotFactoryRef });

  const derivedState = useAppDerivedState(appState);
  const {
    loadedModels,
    loadedModelNames,
    sceneOrganizationObjects,
    behaviorScriptContext,
    behaviorCodeTargets,
    scenePrimitives,
    selectedTransform,
    selectedProjectPosition,
    selectionName,
    selectionVisible,
    selectionOpacity,
    selectionColor,
    selectionMaterial,
    selectedEffects,
    selectedPhysics,
    selectionProperties,
    selectedLayerId,
    selectedComponent,
    selectedBehaviorTarget,
    selectionLocked,
    componentFacets,
    floorStates,
    floorStatesByModel,
    selectedLight,
    componentResults,
    componentSearchActive,
    collisions,
    spaces,
    selectedAnnotation,
    clippingRange,
    clippingSceneBounds,
    explosionFactor,
    explosionMode,
    sceneStatistics,
  } = derivedState;

  const sceneEditorController = createSceneEditorController({
    engine,
    project,
    locale,
    selected,
    selectedLayerId,
    selectedEffects,
    selectedPhysics,
    sceneCoordinates,
    sceneEnvironment,
    lighting,
    clipping,
    explosionMode,
    floorStatesByModel,
    sceneOrganizationObjects,
    sceneOrganizationSelection,
    selectionSets,
    rootLayerOrder,
    setRootLayerOrder,
    lastDeletedSelectionSet,
    annotations,
    annotationEnabled,
    measureEnabled,
    measureMode,
    navigationSettings,
    cameraViews,
    cameraConstraints,
    sceneAnimation,
    animationTime,
    animationPlaying,
    rvtConversionMode,
    rvtRevitVersion,
    uploadRef,
    environmentMapRef,
    materialTextureRef,
    materialTextureKindRef,
    primitiveColors,
    refreshProject,
    showError,
    setUploading,
    setBusy,
    setMessage,
    setRevision,
    setSelected,
    setMeasurements,
    setAnnotations,
    setAnnotationEnabled,
    setSelectedAnnotationId,
    setSceneInteractions,
    setSceneDataBindings,
    setNavigationMode,
    setTransformMode,
    setMeasureEnabled,
    setMeasureMode,
    setClippingState,
    setWeather,
    setLighting,
    setSceneEnvironment,
    setPostProcessing,
    setPhysics,
    engineeringAnalysis,
    setEngineeringAnalysis,
    setEnvironmentOpen,
    setSelectedLightId,
    setCameraViews,
    setCameraConstraints,
    setDefaultCameraViewId,
    setNavigationSettings,
    setFloorExpansionByModel,
    setExpandedModels,
    setSceneOrganizationSelection,
    setSelectionSets,
    setLastDeletedSelectionSet,
    setXrPanelOpen,
    setSceneAnimation,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
    runSceneEdit: sceneHistoryState.runSceneHistoryEdit,
  });
  const {
    loadModel,
    uploadModels,
    deleteModel,
    beginPrimitivePlacement,
    deletePrimitive,
    removeObjectInteractions,
    deleteMeasurement,
    toggleAnnotationPlacement,
    updateAnnotation,
    updateAnnotationPosition,
    deleteAnnotation,
    changeNavigation,
    changeTransform,
    toggleMeasurement,
    changeMeasureMode,
    focusComponent,
    updateClipping,
    changeClippingMode,
    updateClippingBox,
    toggleClipping,
    updateExplosion,
    updateSelectedTransform,
    changeWeather,
    changeLighting,
    changeSceneEnvironment,
    changePostProcessing,
    changePhysics,
    changeSelectedPhysics,
    uploadEnvironmentMap,
    updateLight,
    addLight,
    removeLight,
    updateSelectionMaterial,
    updateSelectedEffects,
    updateSelectionColor,
    updateSelectionOpacity,
    updateSelectionVisibility,
    addCameraView,
    changeCameraConstraints,
    uploadMaterialTexture,
    chooseMaterialTexture,
    changeNavigationSettings,
    updateCameraViewName,
    replaceCameraView,
    removeCameraView,
    updateFloor,
    expandFloors,
    replaceSceneOrganizationSelection,
    toggleSceneOrganizationObject,
    setSceneObjectsVisible,
    setSceneObjectsLocked,
    isolateSceneObjects,
    restoreSceneObjectIsolation,
    createSceneSelectionSet,
    createSceneGroup,
    moveSceneObjectsToGroup,
    moveSceneRootEntries,
    reorderSceneGroup,
    renameSceneGroup,
    updateSceneSelectionSet,
    applySceneSelectionSet,
    deleteSceneSelectionSet,
    restoreDeletedSceneSelectionSet,
    selectLightForTransform,
    startXR,
    updateSceneAnimation,
    addCameraKeyframe,
    addModelKeyframe,
    toggleSceneAnimation,
    deleteKeyframe,
  } = sceneEditorController;

  const applicationRuntimeController = createApplicationRuntimeController({
    applicationSessionRef,
    behaviorManagerRef,
    behaviorCommandQueueRef,
    engine,
    project,
    activeScene,
    activeApplication,
    activeTopology,
    managerApplications,
    currentUser,
    route,
    locale,
    sceneBehaviorEntries,
    sceneBehaviorPaused,
    navigate,
    showError,
    sortScenesByTime,
    setActiveScene,
    setAutoSaveEnabled,
    setBusy,
    setExpandedModels,
    setMessage,
    setRevision,
    setSceneBehaviorActive,
    setSceneBehaviorEntries,
    setSceneBehaviorLogs,
    setSceneBehaviorPaused,
    setScenes,
  });
  const {
    toggleModelTree,
    dispatchApplicationCommand,
    restoreScenePublication,
    enablePublishedCloudScene,
    createIndustrialShowcase,
    upsertBehaviorScript,
    deleteBehaviorScript,
    dispatchApplicationInteraction,
    updateComponentFromScript,
    dispatchDashboardNodeInteraction,
    dispatchSceneObjectInteraction,
    saveActiveApplication,
    publishActiveApplication,
    changeAutoSave,
    insertActiveTopologyIntoDashboard,
    enterSceneFromDashboard,
    returnFromSceneEditor,
  } = applicationRuntimeController;

  const publicationArtifacts = useScenePublicationArtifacts(currentUser?.id);
  const scenePersistenceController = createScenePersistenceController({
    buildPublicationArtifact: publicationArtifacts.begin,
    getActiveScene: appState.getActiveScene, getRoute: appState.getRoute, getScenes: appState.getScenes,
    onFirstSceneSave: sceneHistoryState.adoptFirstSavedScene,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
    engine,
    project,
    activeScene,
    activeApplication,
    route,
    locale,
    sceneName,
    revision,
    selected,
    selectedLayerId,
    selectedAnnotationId,
    measurements,
    cameraViews,
    defaultCameraViewId,
    sceneCoordinates,
    sceneDashboard,
    engineeringAnalysis,
    sceneDataBindings,
    sceneAssetBindings,
    sceneInteractions,
    selectionSets,
    rootLayerOrder,
    setRootLayerOrder,
    configuredDefaultEnvironment,
    studioPublishMode,
    studioPublishPerformance,
    scenes,
    applicationSessionRef,
    rendererSnapshotRef,
    webGpuSceneReplacementCountRef,
    sceneNameCommitRef,
    sceneApplyVersionRef,
    lastAutoSavedSceneRevisionRef,
    primitiveColors,
    importRef,
    navigate,
    loadModel,
    saveActiveApplication,
    enablePublishedCloudScene,
    dispatchApplicationCommand,
    waitForModelReady,
    isModelLoadSuperseded,
    sortScenesByTime,
    showError,
    setActiveScene,
    setAutoSaveEnabled,
    setAnimationPlaying,
    setAnimationTime,
    setAnnotations,
    setAvatarVisible,
    setBusy,
    setCameraConstraints,
    setCameraViews,
    setClippingState,
    setDefaultCameraViewId,
    setLastDeletedSelectionSet,
    setLighting,
    setMeasurements,
    setMessage,
    setNavigationMode,
    setNavigationSettings,
    setPhysics,
    setPostProcessing,
    setEngineeringAnalysis,
    setProject,
    setProjects,
    setRevision,
    setRendererGeneration,
    setRendererSwitching,
    setSceneAnimation,
    setSceneCoordinates,
    setSceneDashboard,
    setSceneDataBindingRuntime,
    setSceneDataBindings,
    setSceneAssetBindings,
    setSceneEnvironment,
    setSceneInteractions,
    setSceneName,
    setSceneOrganizationSelection,
    setScenes,
    setSelected,
    setSelectedAnnotationId,
    setSelectedLightId,
    setSelectedSpace,
    setSelectionSets,
    setStudioPublishOpen,
    setViewerLoadState,
    setWeather,
  });
  const {
    makeSnapshot,
    saveScene,
    browseActiveScene,
    publishActiveScene,
    commitSceneName,
    applyScene,
    ensureApplicationForScene,
    openSceneDashboard,
    openTopologyEditor,
    createScene,
    exportSceneConfig,
    exportSingleFileScene,
    exportGlbScene,
    exportFbxScene,
    importScene,
    deleteScene,
    copyScene,
    renameScene,
    publishScene,
    unpublishScene,
  } = scenePersistenceController;
  useAppSceneSyncEffects({
    state: appState,
    playModeActive: playMode.active,
    recoveryDecisionRef,
    setRecoveryDraft,
    refreshProject,
    navigate,
    applyScene,
    openSceneDashboard,
  });

  sceneSnapshotFactoryRef.current = makeSnapshot;

  useAppLifecycleEffects({
    state: appState,
    playModeActive: playMode.active,
    saveActiveApplication,
    saveScene,
    changeRendererBackend,
  });

  const applicationRecovery = useApplicationRecovery(appState);
  const { undoSceneEdit, redoSceneEdit, restoreRecoveryDraft, deferRecoveryDraft, discardRecoveryDraft } = useSceneHistoryActions({
    state: appState,
    history: sceneHistoryState,
    playModeActive: playMode.active,
    applyScene,
  });

  useAppRuntimeEffects({
    ...appState,
    navigate,
    applyScene,
    dispatchApplicationInteraction,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
    captureSceneSnapshot: () => sceneSnapshotFactoryRef.current?.(),
  });

  const viewBindings: AppViewBindings = {
    managerDirectory,
    state: appState,
    derived: derivedState,
    sceneEditor: sceneEditorController,
    scenePersistence: scenePersistenceController,
    publicationArtifacts,
    applicationRuntime: applicationRuntimeController,
    actions: {
      navigate,
      openDataCenter,
      closeDataCenter,
      openDocs,
      replaceDashboardView,
      changeRendererBackend,
      switchProjectById,
      openProjectDialog,
      submitProjectDialog,
      deleteCurrentProject,
      refreshProject,
    },
    applicationRecovery,
    recovery: {
      draft: recoveryDraft,
      busy: recoveryBusy,
      restore: restoreRecoveryDraft, defer: deferRecoveryDraft, discard: discardRecoveryDraft,
      export: () => { if (recoveryDraft) downloadWorkspaceRecoveryDraft(recoveryDraft); },
    },
    sceneHistory: {
      ...sceneHistoryRef.current.getState(),
      flush: flushSceneHistoryEdit, undo: undoSceneEdit, redo: redoSceneEdit,
    },
    playMode: {
      active: playMode.active,
      enter: () => {
        if (route.view !== "studio" || busy || rendererSwitching || sceneBehaviorOpen || sceneBehaviorActive || !activeScene || !project) return;
        if (sceneNameCommitRef.current || sceneName !== activeScene.name) {
          showError(new Error("场景名称尚未保存，请待名称提交后再播放"));
          return;
        }
        if (animationPlaying || engine?.getPhysicsState().playing) {
          showError(new Error("动画或物理正在运行，请先暂停再进入播放模式"));
          return;
        }
        if (engine?.getAuthorRendererBackend() === "webgpu") {
          showError(new Error("当前 WebGPU 渲染器暂不支持安全的 Play 快照恢复；请先切换 WebGL"));
          return;
        }
        if (sceneHistoryState.sceneEditTransactionRef.current) {
          showError(new Error("场景编辑事务尚未完成，请等待当前操作完成后再播放"));
          return;
        }
        let restricted: RestrictedPlayConsumer;
        try {
          restricted = createRestrictedPlayConsumer({
            scripts: engine?.getInteractionScripts() ?? [],
            host: { engine: engine!, sceneId: activeScene.id },
            onError: showError,
          });
          restricted.start();
        } catch (error) {
          showError(error instanceof Error ? error : new Error(String(error)));
          return;
        }
        if (engine) {
          engine.onRestrictedInteraction = (trigger, target, detail) => restricted.dispatchInteraction(trigger, target, detail);
          engine.onRestrictedPlayFrame = (deltaMs) => restricted.advance(deltaMs);
        }
        const result = playMode.enterPlay();
        if (result.ok) {
          restrictedPlayRef.current = restricted;
          engine?.setContinuousRender("restricted-play", true);
          setMessage("已进入播放模式；修改仅在本次播放期间生效");
        } else {
          if (engine) {
            engine.onRestrictedInteraction = undefined;
            engine.onRestrictedPlayFrame = undefined;
          }
          void restricted.stop();
          if (result.reason === "scene-not-ready") showError(new Error("场景尚未完整载入，请稍后重试进入播放"));
          else if (result.reason === "engine-missing") showError(new Error("三维引擎尚未就绪，请稍后重试进入播放"));
        }
      },
      exit: async () => {
        const restricted = restrictedPlayRef.current;
        if (engine) {
          engine.onRestrictedInteraction = undefined;
          engine.onRestrictedPlayFrame = undefined;
          engine.setContinuousRender("restricted-play", false);
        }
        await restricted?.stop();
        const result = await playMode.exitPlay();
        if (result.ok) {
          restrictedPlayRef.current = undefined;
          setMessage("已退出播放模式，场景恢复为进入前状态");
        } else {
          showError(new Error("播放已停止受限脚本，但场景恢复未完成；请再次点击退出播放重试。"));
        }
      },
    },
  };

  return <>
    <NetworkStatusBanner />
    <AppRootView bindings={viewBindings} onOpenDocs={openDocs} onCloseDocs={closeDocs} />
  </>;
}
