import type { ProjectRecord, SceneSnapshot } from "@bim-studio/contracts";
import { api } from "./api";
import { createApplicationRuntimeController } from "./controllers/applicationRuntimeController";
import { createSceneEditorController } from "./controllers/sceneEditorController";
import { createScenePersistenceController } from "./controllers/scenePersistenceController";
import { useAppDerivedState } from "./hooks/useAppDerivedState";
import { useGlobalDialogEscape } from "./hooks/useGlobalDialogEscape";
import { useAppLifecycleEffects } from "./hooks/useAppLifecycleEffects";
import { useAppNavigationController } from "./hooks/useAppNavigationController";
import { useAppRuntimeEffects } from "./hooks/useAppRuntimeEffects";
import { useAppSceneSyncEffects } from "./hooks/useAppSceneSyncEffects";
import { useAppState } from "./hooks/useAppState";
import { useSceneHistoryActions } from "./hooks/useSceneHistoryActions";
import { useApplicationRecovery } from "./hooks/useApplicationRecovery";
import { useSceneHistoryState } from "./hooks/useSceneHistoryState";
import { downloadWorkspaceRecoveryDraft } from "./studio/workspaceRecoveryStore";
import type { AppViewBindings } from "./views/appViewBindings";
import { AppRootView } from "./views/AppRootView";
import { NetworkStatusBanner } from "./appStatus/NetworkStatusBanner";

function sortScenesByTime(items: SceneSnapshot[]): SceneSnapshot[] {
  return [...items].sort((left, right) => Date.parse(right.updatedAt) - Date.parse(left.updatedAt));
}
function isModelLoadSuperseded(reason: unknown): boolean {
  return reason instanceof Error && reason.name === "ModelLoadSupersededError";
}
async function waitForModelReady(projectId: string, modelId: string): Promise<ProjectRecord> {
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    const current = await api.getProject(projectId);
    const model = current.models.find((item) => item.id === modelId);
    if (!model) throw new Error("导入的模型资源不存在");
    if (model.status === "ready") return current;
    if (model.status === "failed" || model.status === "waiting_converter") throw new Error(model.message);
    await new Promise((resolve) => window.setTimeout(resolve, 250));
  }
  throw new Error("模型资源处理超时，请稍后在项目资源中查看");
}

export function App() {
  const appState = useAppState();
  useGlobalDialogEscape();
  const {
    initialPathRef,
    defaultEntryAppliedRef,
    viewportRef,
    uploadRef,
    importRef,
    environmentMapRef,
    materialTextureRef,
    materialTextureKindRef,
    sceneNameCommitRef,
    sceneApplyVersionRef,
    sceneWorkspaceLoadRef,
    rendererSnapshotRef,
    webGpuSceneReplacementCountRef,
    applicationSessionRef,
    activeSceneIdRef,
    pendingSceneFocusRef,
    visionEventCursorRef,
    behaviorManagerRef,
    behaviorCommandQueueRef,
    engine,
    setEngine,
    currentUser,
    setCurrentUser,
    branding,
    setBranding,
    authReady,
    setAuthReady,
    rendererBackend,
    setRendererBackend,
    rendererSwitching,
    setRendererSwitching,
    rendererGeneration,
    setRendererGeneration,
    rendererDiagnosticsOpen,
    setRendererDiagnosticsOpen,
    systemInitialTab,
    setSystemInitialTab,
    studioPublishMode,
    setStudioPublishMode,
    studioPublishPerformance,
    setStudioPublishPerformance,
    studioPublishOpen,
    setStudioPublishOpen,
    studioCloudConfigured,
    setStudioCloudConfigured,
    studioCloudHint,
    setStudioCloudHint,
    projects,
    setProjects,
    project,
    setProject,
    scenes,
    setScenes,
    managerApplications,
    setManagerApplications,
    activeScene,
    setActiveScene,
    applicationRevision,
    setApplicationRevision,
    sceneName,
    setSceneName,
    selected,
    setSelected,
    measurements,
    setMeasurements,
    revision,
    setRevision,
    uploading,
    setUploading,
    rvtConversionMode,
    setRvtConversionMode,
    revitRuntime,
    setRevitRuntime,
    rvtRevitVersion,
    setRvtRevitVersion,
    busy,
    setBusy,
    viewerLoadState,
    setViewerLoadState,
    autoSaveEnabled,
    setAutoSaveEnabled,
    lastAutoSavedSceneRevisionRef,
    message,
    setMessage,
    error,
    setError,
    measureEnabled,
    setMeasureEnabled,
    annotationEnabled,
    setAnnotationEnabled,
    annotations,
    setAnnotations,
    selectedAnnotationId,
    setSelectedAnnotationId,
    selectedSpace,
    setSelectedSpace,
    transformMode,
    setTransformMode,
    selectionScope,
    setSelectionScope,
    navigationMode,
    setNavigationMode,
    navigationDiagnostics,
    setNavigationDiagnostics,
    measureMode,
    setMeasureMode,
    route,
    setRoute,
    dataReturnRouteRef,
    viewerRouteActive,
    applicationState,
    activeApplication,
    activeDashboardPage,
    activeTopology,
    topologyDataProducts,
    setTopologyDataProducts,
    topologyRuntimeStates,
    setTopologyRuntimeStates,
    avatarVisible,
    setAvatarVisible,
    cameraInfo,
    setCameraInfo,
    pointerInfo,
    setPointerInfo,
    infoEnabled,
    setInfoEnabled,
    frameRate,
    setFrameRate,
    weather,
    setWeather,
    environmentOpen,
    setEnvironmentOpen,
    lighting,
    setLighting,
    sceneEnvironment,
    setSceneEnvironment,
    sceneCoordinates,
    setSceneCoordinates,
    configuredDefaultEnvironment,
    postProcessing,
    setPostProcessing,
    physics,
    setPhysics,
    physicsOpen,
    setPhysicsOpen,
    selectedLightId,
    setSelectedLightId,
    creditsOpen,
    setCreditsOpen,
    digitalTwinOpen,
    setDigitalTwinOpen,
    sceneDataStatus,
    setSceneDataStatus,
    sceneDataReceived,
    setSceneDataReceived,
    aiAssistantOpen,
    setAiAssistantOpen,
    sceneDashboard,
    setSceneDashboard,
    sceneDataBindings,
    setSceneDataBindings,
    sceneAssetBindings,
    setSceneAssetBindings,
    sceneDataBindingRuntime,
    setSceneDataBindingRuntime,
    sceneInteractions,
    setSceneInteractions,
    viewerToolsOpen,
    setViewerToolsOpen,
    xrPanelOpen,
    setXrPanelOpen,
    xrActiveMode,
    setXrActiveMode,
    xrCapabilities,
    setXrCapabilities,
    locale,
    setLocale,
    sceneAnimation,
    setSceneAnimation,
    cameraViews,
    setCameraViews,
    cameraConstraints,
    setCameraConstraints,
    navigationSettings,
    setNavigationSettings,
    defaultCameraViewId,
    setDefaultCameraViewId,
    cameraViewsOpen,
    setCameraViewsOpen,
    animationTime,
    setAnimationTime,
    animationPlaying,
    setAnimationPlaying,
    animationOpen,
    setAnimationOpen,
    componentQuery,
    setComponentQuery,
    componentLevel,
    setComponentLevel,
    componentCategory,
    setComponentCategory,
    floorExpansionByModel,
    setFloorExpansionByModel,
    clipping,
    setClippingState,
    expandedModels,
    setExpandedModels,
    sceneOrganizationOpen,
    setSceneOrganizationOpen,
    sceneImportOpen,
    setSceneImportOpen,
    sceneBehaviorOpen,
    setSceneBehaviorOpen,
    sceneBehaviorActive,
    setSceneBehaviorActive,
    sceneBehaviorPaused,
    setSceneBehaviorPaused,
    sceneBehaviorEntries,
    setSceneBehaviorEntries,
    sceneBehaviorLogs,
    setSceneBehaviorLogs,
    inspectorTab,
    setInspectorTab,
    sceneOrganizationSelection,
    setSceneOrganizationSelection,
    selectionSets,
    setSelectionSets,
    lastDeletedSelectionSet,
    setLastDeletedSelectionSet,
    projectDialogMode,
    setProjectDialogMode,
    newProjectName,
    setNewProjectName,
    newProjectDescription,
    setNewProjectDescription,
    primitiveColors,
    interactionTargetOptions,
    showError,
    rendererDiagnostics,
  } = appState;
  const sceneHistoryState = useSceneHistoryState({ activeScene, routeView: route.view, sceneBehaviorActive, animationPlaying });
  const {
    recoveryDraft,
    setRecoveryDraft,
    recoveryBusy,
    setRecoveryBusy,
    recoveryDecisionRef,
    sceneHistoryRef,
    sceneSnapshotFactoryRef,
    sceneHistoryApplyingRef,
    sceneHistoryRecordRef,
    sceneHistoryRevision,
    flushSceneHistoryEdit,
  } = sceneHistoryState;

  const {
    managerDirectory,
    navigate,
    openDataCenter,
    closeDataCenter,
    openDocs,
    closeDocs,
    replaceDashboardView,
    changeRendererBackend,
    switchProject,
    switchProjectById,
    openProjectDialog,
    submitProjectDialog,
    deleteCurrentProject,
    refreshProject,
  } = useAppNavigationController({ state: appState, sceneSnapshotFactoryRef });

  const derivedState = useAppDerivedState(appState);
  const {
    loadedModels,
    loadedModelNames,
    sceneOrganizationObjects,
    behaviorScriptContext,
    behaviorCodeTargets,
    scenePrimitives,
    selectedTransform,
    selectedProjectPosition,
    selectionName,
    selectionVisible,
    selectionOpacity,
    selectionColor,
    selectionMaterial,
    selectedEffects,
    selectedPhysics,
    selectionProperties,
    selectedLayerId,
    selectedComponent,
    selectedBehaviorTarget,
    selectionLocked,
    componentFacets,
    floorStates,
    floorStatesByModel,
    selectedLight,
    componentResults,
    componentSearchActive,
    collisions,
    spaces,
    selectedAnnotation,
    clippingRange,
    clippingSceneBounds,
    explosionFactor,
    explosionMode,
    sceneStatistics,
  } = derivedState;

  const sceneEditorController = createSceneEditorController({
    engine,
    project,
    locale,
    selected,
    selectedLayerId,
    selectedEffects,
    selectedPhysics,
    sceneCoordinates,
    sceneEnvironment,
    lighting,
    clipping,
    explosionMode,
    floorStatesByModel,
    sceneOrganizationObjects,
    sceneOrganizationSelection,
    selectionSets,
    lastDeletedSelectionSet,
    annotations,
    annotationEnabled,
    measureEnabled,
    measureMode,
    navigationSettings,
    cameraViews,
    cameraConstraints,
    sceneAnimation,
    animationTime,
    animationPlaying,
    rvtConversionMode,
    rvtRevitVersion,
    uploadRef,
    environmentMapRef,
    materialTextureRef,
    materialTextureKindRef,
    primitiveColors,
    refreshProject,
    showError,
    setUploading,
    setBusy,
    setMessage,
    setRevision,
    setSelected,
    setMeasurements,
    setAnnotations,
    setAnnotationEnabled,
    setSelectedAnnotationId,
    setSceneInteractions,
    setSceneDataBindings,
    setNavigationMode,
    setTransformMode,
    setMeasureEnabled,
    setMeasureMode,
    setClippingState,
    setWeather,
    setLighting,
    setSceneEnvironment,
    setPostProcessing,
    setPhysics,
    setEnvironmentOpen,
    setSelectedLightId,
    setCameraViews,
    setCameraConstraints,
    setDefaultCameraViewId,
    setNavigationSettings,
    setFloorExpansionByModel,
    setExpandedModels,
    setSceneOrganizationSelection,
    setSelectionSets,
    setLastDeletedSelectionSet,
    setXrPanelOpen,
    setSceneAnimation,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
  });
  const {
    loadModel,
    uploadModels,
    deleteModel,
    beginPrimitivePlacement,
    deletePrimitive,
    removeObjectInteractions,
    deleteMeasurement,
    toggleAnnotationPlacement,
    updateAnnotation,
    updateAnnotationPosition,
    deleteAnnotation,
    changeNavigation,
    changeTransform,
    toggleMeasurement,
    changeMeasureMode,
    focusComponent,
    updateClipping,
    changeClippingMode,
    updateClippingBox,
    toggleClipping,
    updateExplosion,
    updateSelectedTransform,
    changeWeather,
    changeLighting,
    changeSceneEnvironment,
    changePostProcessing,
    changePhysics,
    changeSelectedPhysics,
    uploadEnvironmentMap,
    updateLight,
    addLight,
    removeLight,
    updateSelectionMaterial,
    updateSelectedEffects,
    updateSelectionColor,
    updateSelectionOpacity,
    updateSelectionVisibility,
    addCameraView,
    changeCameraConstraints,
    uploadMaterialTexture,
    chooseMaterialTexture,
    changeNavigationSettings,
    updateCameraViewName,
    replaceCameraView,
    removeCameraView,
    updateFloor,
    expandFloors,
    replaceSceneOrganizationSelection,
    toggleSceneOrganizationObject,
    setSceneObjectsVisible,
    setSceneObjectsLocked,
    isolateSceneObjects,
    restoreSceneObjectIsolation,
    createSceneSelectionSet,
    createSceneGroup,
    moveSceneObjectsToGroup,
    reorderSceneGroup,
    renameSceneGroup,
    updateSceneSelectionSet,
    applySceneSelectionSet,
    deleteSceneSelectionSet,
    restoreDeletedSceneSelectionSet,
    selectLightForTransform,
    startXR,
    updateSceneAnimation,
    addCameraKeyframe,
    addModelKeyframe,
    toggleSceneAnimation,
    deleteKeyframe,
  } = sceneEditorController;

  const applicationRuntimeController = createApplicationRuntimeController({
    applicationSessionRef,
    behaviorManagerRef,
    behaviorCommandQueueRef,
    engine,
    project,
    activeScene,
    activeApplication,
    activeTopology,
    managerApplications,
    currentUser,
    route,
    locale,
    sceneBehaviorEntries,
    sceneBehaviorPaused,
    navigate,
    showError,
    sortScenesByTime,
    setActiveScene,
    setAutoSaveEnabled,
    setBusy,
    setExpandedModels,
    setMessage,
    setRevision,
    setSceneBehaviorActive,
    setSceneBehaviorEntries,
    setSceneBehaviorLogs,
    setSceneBehaviorPaused,
    setScenes,
  });
  const {
    toggleModelTree,
    dispatchApplicationCommand,
    restoreScenePublication,
    enablePublishedCloudScene,
    createIndustrialShowcase,
    upsertBehaviorScript,
    deleteBehaviorScript,
    dispatchApplicationInteraction,
    updateComponentFromScript,
    dispatchDashboardNodeInteraction,
    dispatchSceneObjectInteraction,
    saveActiveApplication,
    publishActiveApplication,
    changeAutoSave,
    insertActiveTopologyIntoDashboard,
    enterSceneFromDashboard,
    returnFromSceneEditor,
  } = applicationRuntimeController;

  const scenePersistenceController = createScenePersistenceController({
    getActiveScene: appState.getActiveScene,
    onFirstSceneSave: sceneHistoryState.adoptFirstSavedScene,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
    engine,
    project,
    activeScene,
    activeApplication,
    route,
    locale,
    sceneName,
    revision,
    selected,
    selectedLayerId,
    selectedAnnotationId,
    measurements,
    cameraViews,
    defaultCameraViewId,
    sceneCoordinates,
    sceneDashboard,
    sceneDataBindings,
    sceneAssetBindings,
    sceneInteractions,
    selectionSets,
    configuredDefaultEnvironment,
    studioPublishMode,
    studioPublishPerformance,
    scenes,
    applicationSessionRef,
    rendererSnapshotRef,
    webGpuSceneReplacementCountRef,
    sceneNameCommitRef,
    sceneApplyVersionRef,
    lastAutoSavedSceneRevisionRef,
    primitiveColors,
    importRef,
    navigate,
    loadModel,
    saveActiveApplication,
    enablePublishedCloudScene,
    dispatchApplicationCommand,
    waitForModelReady,
    isModelLoadSuperseded,
    sortScenesByTime,
    showError,
    setActiveScene,
    setAutoSaveEnabled,
    setAnimationPlaying,
    setAnimationTime,
    setAnnotations,
    setAvatarVisible,
    setBusy,
    setCameraConstraints,
    setCameraViews,
    setClippingState,
    setDefaultCameraViewId,
    setLastDeletedSelectionSet,
    setLighting,
    setMeasurements,
    setMessage,
    setNavigationMode,
    setNavigationSettings,
    setPhysics,
    setPostProcessing,
    setProject,
    setProjects,
    setRevision,
    setRendererGeneration,
    setRendererSwitching,
    setSceneAnimation,
    setSceneCoordinates,
    setSceneDashboard,
    setSceneDataBindingRuntime,
    setSceneDataBindings,
    setSceneAssetBindings,
    setSceneEnvironment,
    setSceneInteractions,
    setSceneName,
    setSceneOrganizationSelection,
    setScenes,
    setSelected,
    setSelectedAnnotationId,
    setSelectedLightId,
    setSelectedSpace,
    setSelectionSets,
    setStudioPublishOpen,
    setViewerLoadState,
    setWeather,
  });
  const {
    makeSnapshot,
    saveScene,
    browseActiveScene,
    publishActiveScene,
    commitSceneName,
    applyScene,
    ensureApplicationForScene,
    openSceneDashboard,
    openTopologyEditor,
    createScene,
    exportSceneConfig,
    exportSingleFileScene,
    exportGlbScene,
    exportFbxScene,
    importScene,
    deleteScene,
    copyScene,
    renameScene,
    publishScene,
    unpublishScene,
  } = scenePersistenceController;
  useAppSceneSyncEffects({
    state: appState,
    recoveryDecisionRef,
    setRecoveryDraft,
    refreshProject,
    navigate,
    applyScene,
    openSceneDashboard,
  });

  sceneSnapshotFactoryRef.current = makeSnapshot;

  useAppLifecycleEffects({
    state: appState,
    saveActiveApplication,
    saveScene,
    changeRendererBackend,
  });

  const applicationRecovery = useApplicationRecovery(appState);
  const { undoSceneEdit, redoSceneEdit, restoreRecoveryDraft, deferRecoveryDraft, discardRecoveryDraft } = useSceneHistoryActions({
    state: appState,
    history: sceneHistoryState,
    applyScene,
  });

  useAppRuntimeEffects({
    authReady,
    currentUser,
    viewerRouteActive,
    viewportRef,
    rendererBackend,
    rendererGeneration,
    engine,
    route,
    locale,
    project,
    activeScene,
    activeApplication,
    applicationState,
    scenes,
    cameraViews,
    infoEnabled,
    xrPanelOpen,
    studioPublishOpen,
    sceneBehaviorActive,
    sceneBehaviorPaused,
    sceneDataBindings,
    sceneInteractions,
    activeSceneIdRef,
    rendererSnapshotRef,
    webGpuSceneReplacementCountRef,
    visionEventCursorRef,
    behaviorManagerRef,
    primitiveColors,
    navigate,
    applyScene,
    dispatchApplicationInteraction,
    recordSceneEdit: (label) => sceneHistoryRecordRef.current(label),
    captureSceneSnapshot: () => sceneSnapshotFactoryRef.current?.(),
    showError,
    setEngine,
    setRendererSwitching,
    setRevision,
    setSelected,
    setSceneOrganizationSelection,
    setSelectedSpace,
    setSelectedLightId,
    setMeasurements,
    setAnnotations,
    setSelectedAnnotationId,
    setLighting,
    setClippingState,
    setCameraInfo,
    setPointerInfo,
    setNavigationDiagnostics,
    setFrameRate,
    setAnimationTime,
    setAnimationPlaying,
    setXrActiveMode,
    setXrCapabilities,
    setStudioCloudConfigured,
    setStudioCloudHint,
    setSceneDataStatus,
    setSceneDataReceived,
    setSceneDataBindingRuntime,
    setSceneBehaviorActive,
    setSceneBehaviorPaused,
    setSceneBehaviorEntries,
    setViewerToolsOpen,
    setMessage,
    setRoute,
    setRendererBackend,
  });

  const viewBindings: AppViewBindings = {
    managerDirectory,
    state: appState,
    derived: derivedState,
    sceneEditor: sceneEditorController,
    scenePersistence: scenePersistenceController,
    applicationRuntime: applicationRuntimeController,
    actions: {
      navigate,
      openDataCenter,
      closeDataCenter,
      openDocs,
      replaceDashboardView,
      changeRendererBackend,
      switchProjectById,
      openProjectDialog,
      submitProjectDialog,
      deleteCurrentProject,
      refreshProject,
    },
    applicationRecovery,
    recovery: {
      draft: recoveryDraft,
      busy: recoveryBusy,
      restore: restoreRecoveryDraft,
      export: () => {
        if (recoveryDraft) downloadWorkspaceRecoveryDraft(recoveryDraft);
      },
      defer: deferRecoveryDraft,
      discard: discardRecoveryDraft,
    },
    sceneHistory: {
      ...sceneHistoryRef.current.getState(),
      flush: flushSceneHistoryEdit,
      undo: undoSceneEdit,
      redo: redoSceneEdit,
    },
  };

  return <>
    <NetworkStatusBanner />
    <AppRootView bindings={viewBindings} onOpenDocs={openDocs} onCloseDocs={closeDocs} />
  </>;
}
