import type { DashboardComponentPreset } from "./dashboardComponentPresetTypes";
import { analysisPreset } from "./dashboardComponentPresetFactory";

/** 基础与高级分析预设共享现有图表运行时，每项携带可直接绑定的字段语义。 */
export const DASHBOARD_ANALYSIS_PRESETS: readonly DashboardComponentPreset[] = [
  analysisPreset("dual-axis-trend", "产值与同比趋势", "Output and YoY", "柱线双轴对照产值和同比变化", "combo", "business.trend", "date", "value", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "value", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["同比"] } }),
  analysisPreset("stacked-category", "分类堆叠分析", "Stacked categories", "按产品与状态拆解分类结构", "bar", "category.structure", "category", "value", { analysis: { dimensionField: "category", seriesField: "series", measureField: "value", aggregation: "sum", sort: "value-desc" }, chart: { stacked: true, showLegend: true } }),
  analysisPreset("structure-ring", "产品结构环图", "Product composition", "汇总产品族占比并支持点击联动", "pie", "structure.share", "category", "value", { linkageParameterKey: "filter.category", analysis: { dimensionField: "category", measureField: "value", aggregation: "sum", sort: "value-desc", limit: 12 } }),
  analysisPreset("conversion-funnel", "工序转化漏斗", "Process funnel", "观察各工序投入、通过和流失", "funnel", "conversion.stage", "stage", "count", { analysis: { dimensionField: "stage", measureField: "count", aggregation: "sum", sort: "value-desc", limit: 8 } }),
  analysisPreset("health-radar", "设备健康雷达", "Asset health radar", "比较振动、温度、润滑与负载评分", "radar", "health.dimension", "dimension", "score", { analysis: { dimensionField: "dimension", measureField: "score", aggregation: "average", limit: 8 } }),
  analysisPreset("risk-scatter", "风险矩阵散点", "Risk scatter", "用概率和影响定位高风险设备", "scatter", "risk.scatter", "asset", "risk", { analysis: { dimensionField: "asset", seriesField: "riskLevel", measureField: "risk", aggregation: "average" } }),
  analysisPreset("process-sankey", "工艺流向桑基", "Process Sankey", "表达工艺路径、流量和损耗去向", "sankey", "process.flow", "source", "flow", { analysis: { dimensionField: "source", seriesField: "target", measureField: "flow", aggregation: "sum" } }),
  analysisPreset("hierarchy-sunburst", "资产层级旭日", "Asset hierarchy", "按工厂、车间、产线和设备逐级钻取", "sunburst", "hierarchy.value", "factory", "value", { analysis: { dimensionField: "factory", measureField: "value", aggregation: "sum", drillFields: ["factory", "workshop", "line", "asset"] } }),
  analysisPreset("capacity-treemap", "产能矩形树图", "Capacity treemap", "面积表达各产线和设备的有效产能", "treemap", "capacity.distribution", "line", "capacity", { analysis: { dimensionField: "line", measureField: "capacity", aggregation: "sum", drillFields: ["line", "station", "asset"] } }),
  analysisPreset("relationship-graph", "设备关系网络", "Asset relationship", "展示设备、工艺与上下游依赖关系", "graph", "relationship.graph", "source", "weight", { analysis: { dimensionField: "source", seriesField: "target", measureField: "weight", aggregation: "sum" } }),
  analysisPreset("regional-risk-map", "区域风险地图", "Regional risk map", "按行政或园区区域着色并点击联动", "map", "regional.risk", "region", "risk", { linkageParameterKey: "filter.region", map: { mode: "region", regionField: "region", valueField: "risk" } }),
  analysisPreset("ranking-analysis", "产线绩效排行", "Line performance ranking", "聚合并降序显示表现前十的产线", "rank", "ranking.value", "line", "score", { field: "score", analysis: { dimensionField: "line", measureField: "score", aggregation: "average", sort: "value-desc", limit: 10 } }),
  analysisPreset("output-shift-trend", "班次产量趋势", "Shift output trend", "按小时查看各班次产量变化", "line", "production.shiftTrend", "hour", "output", { analysis: { dimensionField: "hour", seriesField: "shift", measureField: "output", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("energy-load-area", "能源负荷曲线", "Energy load area", "以面积趋势观察电力和蒸汽负荷", "area", "energy.load", "timestamp", "consumption", { analysis: { dimensionField: "timestamp", seriesField: "energyType", measureField: "consumption", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("downtime-pareto", "停机原因帕累托", "Downtime Pareto", "按累计停机时长识别主要损失原因", "combo", "downtime.pareto", "reason", "minutes", { analysis: { dimensionField: "reason", seriesField: "metric", measureField: "minutes", aggregation: "sum", sort: "value-desc", limit: 12 }, chart: { showDataLabels: true, secondaryAxisSeries: ["累计占比"] } }),
  analysisPreset("station-throughput", "工位吞吐对比", "Station throughput", "横向比较瓶颈工位的单位时间产出", "bar", "station.throughput", "station", "throughput", { analysis: { dimensionField: "station", measureField: "throughput", aggregation: "average", sort: "value-asc" }, chart: { showDataLabels: true } }),
  analysisPreset("quality-defect-share", "缺陷类型占比", "Defect share", "统计不同缺陷类型的数量占比", "pie", "quality.defects", "defectType", "count", { analysis: { dimensionField: "defectType", measureField: "count", aggregation: "sum", sort: "value-desc", limit: 10 }, chart: { showLegend: true } }),
  analysisPreset("cycle-output-scatter", "节拍产量散点", "Cycle/output scatter", "识别节拍异常与产量偏离的关联", "scatter", "production.cycleOutput", "cycleTime", "output", { analysis: { dimensionField: "cycleTime", seriesField: "line", measureField: "output", aggregation: "average" } }),
  analysisPreset("shift-capability-radar", "班组能力雷达", "Shift capability radar", "比较安全、质量、交付、成本和效率", "radar", "shift.capability", "dimension", "score", { analysis: { dimensionField: "dimension", seriesField: "shift", measureField: "score", aggregation: "average" }, chart: { showLegend: true } }),
  analysisPreset("material-loss-funnel", "物料损耗漏斗", "Material loss funnel", "跟踪领料、投料、良品和入库数量", "funnel", "material.loss", "stage", "quantity", { analysis: { dimensionField: "stage", measureField: "quantity", aggregation: "sum" } }),
  analysisPreset("energy-flow-sankey", "能源流向桑基", "Energy flow Sankey", "追踪能源从入口到车间设备的分配", "sankey", "energy.flow", "source", "energy", { analysis: { dimensionField: "source", seriesField: "target", measureField: "energy", aggregation: "sum" } }),
  analysisPreset("organization-sunburst", "组织成本旭日", "Organization cost", "按公司、部门和成本中心逐级分析", "sunburst", "organization.cost", "company", "cost", { analysis: { dimensionField: "company", measureField: "cost", aggregation: "sum", drillFields: ["company", "department", "costCenter"] } }),
  analysisPreset("maintenance-cost-tree", "维护成本树图", "Maintenance cost tree", "按设备类型和故障模式拆解维护支出", "treemap", "maintenance.cost", "assetType", "cost", { analysis: { dimensionField: "assetType", measureField: "cost", aggregation: "sum", drillFields: ["assetType", "failureMode", "asset"] } }),
  analysisPreset("supply-dependency-graph", "供应依赖关系", "Supply dependency", "展示物料、供应商和产线的依赖网络", "graph", "supply.dependencies", "supplier", "volume", { analysis: { dimensionField: "supplier", seriesField: "material", measureField: "volume", aggregation: "sum" } }),
  analysisPreset("site-alarm-heatmap", "园区告警热力", "Site alarm heatmap", "以经纬度热力展示告警密集区域", "map", "site.alarmHeat", "site", "alarmCount", { map: { mode: "heat", longitudeField: "longitude", latitudeField: "latitude", valueField: "alarmCount" } }),
  analysisPreset("logistics-route-map", "物流路线地图", "Logistics route map", "显示车辆、AGV 和配送路线的空间轨迹", "map", "logistics.routes", "route", "distance", { map: { mode: "route", longitudeField: "longitude", latitudeField: "latitude", valueField: "distance" } }),
  analysisPreset("asset-location-map", "设备点位地图", "Asset location map", "按经纬度定位场站与设备并联动筛选", "map", "asset.locations", "asset", "statusCode", { linkageParameterKey: "filter.asset", map: { mode: "scatter", longitudeField: "longitude", latitudeField: "latitude", valueField: "statusCode" } }),
  analysisPreset("plan-actual-combo", "计划实绩对比", "Plan vs actual", "柱形对比计划与实绩并叠加达成率", "combo", "production.planActual", "date", "value", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "value", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["达成率"] } }),
  analysisPreset("vibration-history", "振动历史趋势", "Vibration history", "观察设备振动均方根与峰值变化", "line", "maintenance.vibration", "timestamp", "vibration", { analysis: { dimensionField: "timestamp", seriesField: "axis", measureField: "vibration", aggregation: "average" }, chart: { showLegend: true } }),
  analysisPreset("anomaly-confidence-area", "异常置信区间", "Anomaly confidence", "展示异常评分趋势与置信区间带", "area", "ai.anomalyConfidence", "timestamp", "score", { analysis: { dimensionField: "timestamp", seriesField: "band", measureField: "score", aggregation: "average" }, chart: { showLegend: true } }),
] as const;

