import type { DashboardTemplateLayout } from "./dashboardTemplateTypes";

export const DASHBOARD_TEMPLATE_LAYOUTS: readonly DashboardTemplateLayout[] = [
  {
    id: "executive-trend",
    primaryChart: "combo",
    secondaryChart: "pie",
    primaryTitleZh: "目标与趋势",
    primaryTitleEn: "Targets and trend",
    secondaryTitleZh: "结构贡献",
    secondaryTitleEn: "Contribution mix",
    detailType: "table",
    metricTypes: ["digital-flip", "progress", "status", "progress"],
    primaryRatio: 0.62,
    decorationStyle: "title",
  },
  {
    id: "throughput-board",
    primaryChart: "area",
    secondaryChart: "gauge",
    primaryTitleZh: "运行节奏",
    primaryTitleEn: "Operating cadence",
    secondaryTitleZh: "资源负荷",
    secondaryTitleEn: "Resource load",
    detailType: "rank",
    metricTypes: ["digital-flip", "value", "progress", "status"],
    primaryRatio: 0.64,
    decorationStyle: "header-wing",
  },
  {
    id: "quality-explorer",
    primaryChart: "scatter",
    secondaryChart: "bar",
    primaryTitleZh: "波动分布",
    primaryTitleEn: "Variation distribution",
    secondaryTitleZh: "缺口排行",
    secondaryTitleEn: "Gap ranking",
    detailType: "table",
    metricTypes: ["progress", "digital-flip", "value", "status"],
    primaryRatio: 0.58,
    decorationStyle: "frame-notch",
  },
  {
    id: "risk-map",
    primaryChart: "map",
    secondaryChart: "radar",
    primaryTitleZh: "区域态势",
    primaryTitleEn: "Area posture",
    secondaryTitleZh: "风险维度",
    secondaryTitleEn: "Risk dimensions",
    detailType: "rank",
    metricTypes: ["status", "progress", "value", "progress"],
    primaryRatio: 0.63,
    decorationStyle: "neon",
  },
  {
    id: "asset-health",
    primaryChart: "scatter",
    secondaryChart: "gauge",
    primaryTitleZh: "健康与风险",
    primaryTitleEn: "Health and risk",
    secondaryTitleZh: "可用性",
    secondaryTitleEn: "Availability",
    detailType: "rank",
    metricTypes: ["digital-flip", "progress", "status", "value"],
    primaryRatio: 0.61,
    decorationStyle: "bracket",
  },
  {
    id: "energy-mix",
    primaryChart: "line",
    secondaryChart: "sunburst",
    primaryTitleZh: "负荷曲线",
    primaryTitleEn: "Load curve",
    secondaryTitleZh: "介质结构",
    secondaryTitleEn: "Utility mix",
    detailType: "table",
    metricTypes: ["digital-flip", "progress", "value", "progress"],
    primaryRatio: 0.62,
    decorationStyle: "scan",
  },
  {
    id: "supply-flow",
    primaryChart: "sankey",
    secondaryChart: "treemap",
    primaryTitleZh: "供需流向",
    primaryTitleEn: "Supply flow",
    secondaryTitleZh: "容量结构",
    secondaryTitleEn: "Capacity structure",
    detailType: "scroll-table",
    metricTypes: ["digital-flip", "value", "status", "progress"],
    primaryRatio: 0.65,
    decorationStyle: "corner",
  },
  {
    id: "service-funnel",
    primaryChart: "funnel",
    secondaryChart: "bar",
    primaryTitleZh: "服务漏斗",
    primaryTitleEn: "Service funnel",
    secondaryTitleZh: "时效分布",
    secondaryTitleEn: "Timeliness distribution",
    detailType: "scroll-table",
    metricTypes: ["progress", "digital-flip", "progress", "status"],
    primaryRatio: 0.56,
    decorationStyle: "divider",
  },
  {
    id: "finance-portfolio",
    primaryChart: "combo",
    secondaryChart: "treemap",
    primaryTitleZh: "成本收益趋势",
    primaryTitleEn: "Cost and return trend",
    secondaryTitleZh: "组合结构",
    secondaryTitleEn: "Portfolio mix",
    detailType: "table",
    metricTypes: ["digital-flip", "value", "progress", "progress"],
    primaryRatio: 0.64,
    decorationStyle: "frame-notch",
  },
  {
    id: "sustainability-scorecard",
    primaryChart: "line",
    secondaryChart: "radar",
    primaryTitleZh: "长期进展",
    primaryTitleEn: "Long-term progress",
    secondaryTitleZh: "治理评分",
    secondaryTitleEn: "Governance score",
    detailType: "rank",
    metricTypes: ["digital-flip", "value", "progress", "status"],
    primaryRatio: 0.6,
    decorationStyle: "segment",
  },
];
