import type { DashboardTemplateView } from "./dashboardTemplateTypes";

export const DASHBOARD_TEMPLATE_VIEWS: readonly DashboardTemplateView[] = [
  {
    id: "executive",
    nameZh: "经营总览",
    nameEn: "Executive overview",
    goalZh: "快速判断经营目标、服务水平与主要风险。",
    goalEn: "Assess target attainment, service level and principal risks.",
    metricRoles: ["volume", "efficiency", "risk", "service"],
    filterField: "business_unit",
    filterZh: "业务单元",
    filterEn: "Business unit",
    detailZh: "关键经营事项",
    detailEn: "Key business items",
    layoutId: "executive-trend",
  },
  {
    id: "operations",
    nameZh: "运行调度",
    nameEn: "Operations control",
    goalZh: "监控当期负荷、资源可用性与处置节奏。",
    goalEn: "Monitor current load, asset availability and response cadence.",
    metricRoles: ["volume", "asset", "quality", "risk"],
    filterField: "shift",
    filterZh: "班次",
    filterEn: "Shift",
    detailZh: "待调度事项",
    detailEn: "Dispatch queue",
    layoutId: "throughput-board",
  },
  {
    id: "quality",
    nameZh: "质量改善",
    nameEn: "Quality improvement",
    goalZh: "识别波动、合规缺口和优先改善对象。",
    goalEn: "Find variation, compliance gaps and priority improvements.",
    metricRoles: ["quality", "volume", "efficiency", "risk"],
    filterField: "quality_grade",
    filterZh: "质量等级",
    filterEn: "Quality grade",
    detailZh: "质量明细",
    detailEn: "Quality detail",
    layoutId: "quality-explorer",
  },
  {
    id: "risk",
    nameZh: "风险处置",
    nameEn: "Risk response",
    goalZh: "定位高风险区域并跟踪处置闭环。",
    goalEn: "Locate high-risk areas and track closure actions.",
    metricRoles: ["risk", "quality", "asset", "service"],
    filterField: "risk_level",
    filterZh: "风险等级",
    filterEn: "Risk level",
    detailZh: "风险处置清单",
    detailEn: "Risk response list",
    layoutId: "risk-map",
  },
  {
    id: "asset",
    nameZh: "资产与设备",
    nameEn: "Asset performance",
    goalZh: "判断资产健康、可用性与维护优先级。",
    goalEn: "Assess asset health, availability and maintenance priority.",
    metricRoles: ["asset", "efficiency", "risk", "cost"],
    filterField: "asset_class",
    filterZh: "资产类别",
    filterEn: "Asset class",
    detailZh: "资产优先级",
    detailEn: "Asset priorities",
    layoutId: "asset-health",
  },
  {
    id: "energy",
    nameZh: "能源效率",
    nameEn: "Energy efficiency",
    goalZh: "识别负荷变化、能源结构和节能机会。",
    goalEn: "Identify load changes, energy mix and savings opportunities.",
    metricRoles: ["energy", "efficiency", "cost", "carbon"],
    filterField: "energy_medium",
    filterZh: "能源介质",
    filterEn: "Energy medium",
    detailZh: "节能机会",
    detailEn: "Savings opportunities",
    layoutId: "energy-mix",
  },
  {
    id: "supply",
    nameZh: "供需协同",
    nameEn: "Supply coordination",
    goalZh: "追踪流量、容量和供应风险。",
    goalEn: "Track flow, capacity and supply risk.",
    metricRoles: ["flow", "volume", "risk", "cost"],
    filterField: "supply_region",
    filterZh: "供需区域",
    filterEn: "Supply region",
    detailZh: "供需明细",
    detailEn: "Supply detail",
    layoutId: "supply-flow",
  },
  {
    id: "service",
    nameZh: "服务履约",
    nameEn: "Service delivery",
    goalZh: "跟踪服务请求、时效和客户体验。",
    goalEn: "Track requests, timeliness and customer experience.",
    metricRoles: ["service", "volume", "quality", "risk"],
    filterField: "service_channel",
    filterZh: "服务渠道",
    filterEn: "Service channel",
    detailZh: "服务工单",
    detailEn: "Service tickets",
    layoutId: "service-funnel",
  },
  {
    id: "finance",
    nameZh: "成本与收益",
    nameEn: "Cost and return",
    goalZh: "平衡成本、效率和收益结构。",
    goalEn: "Balance cost, efficiency and return structure.",
    metricRoles: ["cost", "volume", "efficiency", "service"],
    filterField: "cost_center",
    filterZh: "成本中心",
    filterEn: "Cost center",
    detailZh: "成本收益明细",
    detailEn: "Cost and return detail",
    layoutId: "finance-portfolio",
  },
  {
    id: "sustainability",
    nameZh: "可持续发展",
    nameEn: "Sustainability",
    goalZh: "跟踪碳排、资源效率与长期改善进展。",
    goalEn: "Track carbon, resource efficiency and long-term improvement.",
    metricRoles: ["carbon", "energy", "quality", "risk"],
    filterField: "reporting_boundary",
    filterZh: "核算边界",
    filterEn: "Reporting boundary",
    detailZh: "可持续行动",
    detailEn: "Sustainability actions",
    layoutId: "sustainability-scorecard",
  },
];
