import type { DashboardComponentPreset } from "./dashboardComponentPresetTypes";
import { utilityPreset } from "./dashboardComponentPresetFactory";

export const DASHBOARD_UTILITY_PRESETS: readonly DashboardComponentPreset[] = [
  utilityPreset({ id: "cascade-filter", category: "control", zh: "级联业务筛选", en: "Cascade filter", descriptionZh: "受上级区域参数约束的业务分类筛选", type: "filter", key: "filter.category", previewFamily: "control", frame: { width: 280, height: 82 }, widget: { filterField: "category", parentFilterKey: "filter.region", options: ["全部", "生产", "仓储", "能源"] } }),
  utilityPreset({ id: "date-filter", category: "control", zh: "业务日期筛选", en: "Date filter", descriptionZh: "按业务日期精确过滤全页组件", type: "filter", key: "filter.date", previewFamily: "control", widget: { filterField: "date", filterMode: "date", filterMatch: "exact" } }),
  utilityPreset({ id: "keyword-filter", category: "control", zh: "设备关键词查询", en: "Asset keyword", descriptionZh: "按设备名称或编码进行包含匹配", type: "filter", key: "filter.keyword", previewFamily: "control", frame: { width: 280, height: 76 }, widget: { filterField: "name", filterMode: "text", filterMatch: "contains" } }),
  utilityPreset({ id: "multi-select-filter", category: "control", zh: "状态多选筛选", en: "Status multi-select", descriptionZh: "同时选择多个运行状态过滤页面", type: "filter", key: "filter.status", previewFamily: "control", frame: { width: 280, height: 110 }, widget: { filterField: "status", filterMode: "multi-select", options: ["运行", "待机", "维护", "故障"] } }),
  utilityPreset({ id: "workshop-filter", category: "control", zh: "车间单选筛选", en: "Workshop selector", descriptionZh: "切换当前关注的车间或区域", type: "filter", key: "filter.workshop", previewFamily: "control", widget: { filterField: "workshop", filterMode: "select", options: ["全部车间", "总装", "焊装", "涂装"] } }),
  utilityPreset({ id: "shift-filter", category: "control", zh: "班次快速切换", en: "Shift selector", descriptionZh: "在早班、中班和晚班数据间切换", type: "filter", key: "filter.shift", previewFamily: "control", widget: { filterField: "shift", filterMode: "select", options: ["全部班次", "早班", "中班", "晚班"] } }),
  utilityPreset({ id: "alarm-level-filter", category: "control", zh: "告警等级多选", en: "Alarm level filter", descriptionZh: "组合筛选提示、一般、重要和紧急告警", type: "filter", key: "filter.alarmLevel", previewFamily: "control", widget: { filterField: "level", filterMode: "multi-select", options: ["提示", "一般", "重要", "紧急"] } }),
  utilityPreset({ id: "order-search", category: "control", zh: "工单编号查询", en: "Work order search", descriptionZh: "按工单编号或设备编码模糊查询", type: "filter", key: "filter.order", previewFamily: "control", widget: { filterField: "orderNo", filterMode: "text", filterMatch: "contains" } }),
  utilityPreset({ id: "operations-summary-text", category: "control", zh: "运营摘要文本", en: "Operations summary", descriptionZh: "承载可编辑的运营结论和班次说明", type: "text", key: "content.operationsSummary", previewFamily: "control", frame: { width: 420, height: 120 }, widget: { content: "今日生产稳定，重点关注待维护设备。", fontSize: 22, fontWeight: 600, textAlign: "left", backgroundOpacity: 0 } }),
  utilityPreset({ id: "maintenance-note-text", category: "control", zh: "维护说明文本", en: "Maintenance note", descriptionZh: "记录维护建议、处置说明和交接事项", type: "text", key: "content.maintenanceNote", previewFamily: "control", frame: { width: 420, height: 140 }, widget: { content: "维护说明", fontSize: 18, fontWeight: 500, textAlign: "left", backgroundOpacity: 0 } }),
  utilityPreset({ id: "status-group-shape", category: "control", zh: "状态分组底板", en: "Status group surface", descriptionZh: "为一组状态卡提供可编辑圆角底板", type: "shape", key: "surface.statusGroup", previewFamily: "control", frame: { width: 520, height: 240 }, widget: { shape: "rounded", color: "#243238", borderColor: "#4b646e", borderWidth: 1, backgroundOpacity: 0.72 } }),

  utilityPreset({ id: "site-plan-image", category: "media", zh: "园区平面图", en: "Site plan image", descriptionZh: "承载用户导入的园区或车间底图", type: "image", key: "media.sitePlan", previewFamily: "media", frame: { width: 560, height: 360 }, widget: { imageFit: "contain", backgroundColor: "#10181c" } }),
  utilityPreset({ id: "equipment-photo", category: "media", zh: "设备现场照片", en: "Equipment photo", descriptionZh: "展示巡检照片并保持画面裁切", type: "image", key: "media.assetPhoto", previewFamily: "media", frame: { width: 360, height: 240 }, widget: { imageFit: "cover" } }),
  utilityPreset({ id: "inspection-video", category: "media", zh: "巡检视频回放", en: "Inspection playback", descriptionZh: "一次播放巡检录像并停在末帧", type: "video", key: "media.inspection", previewFamily: "media", frame: { width: 480, height: 270 }, widget: { videoFit: "contain", videoAutoplay: false, videoMuted: true, videoLoop: false } }),
  utilityPreset({ id: "training-video", category: "media", zh: "作业指导视频", en: "Work instruction video", descriptionZh: "循环播放静音作业指导内容", type: "video", key: "media.instruction", previewFamily: "media", frame: { width: 480, height: 270 }, widget: { videoFit: "cover", videoAutoplay: true, videoMuted: true, videoLoop: true } }),
  utilityPreset({ id: "hls-monitor", category: "media", zh: "HLS 安防监控", en: "HLS security monitor", descriptionZh: "接入标准 HLS 摄像头直播地址", type: "monitor", key: "media.hlsMonitor", previewFamily: "media", frame: { width: 480, height: 270 }, widget: { monitorProtocol: "hls", videoFit: "cover", videoAutoplay: true, videoMuted: true, videoLoop: true } }),
  utilityPreset({ id: "webrtc-monitor", category: "media", zh: "WebRTC 低延迟监控", en: "WebRTC live monitor", descriptionZh: "接入低延迟现场视频流", type: "monitor", key: "media.webrtcMonitor", previewFamily: "media", frame: { width: 480, height: 270 }, widget: { monitorProtocol: "webrtc", videoFit: "cover", videoAutoplay: true, videoMuted: true } }),
  utilityPreset({ id: "embedded-operations-page", category: "media", zh: "嵌入业务页面", en: "Embedded operations page", descriptionZh: "嵌入经过授权的运维或报表页面", type: "url", key: "media.operationsPage", previewFamily: "media", frame: { width: 640, height: 400 }, widget: { url: "about:blank" } }),

  utilityPreset({ id: "gis-region-layer", category: "gis", zh: "区域着色地图", en: "Region choropleth", descriptionZh: "按区域业务值形成分级着色", type: "map", key: "gis.region", previewFamily: "gis", frame: { width: 560, height: 340 }, widget: { map: { mode: "region", regionField: "region", valueField: "value" }, linkageParameterKey: "filter.region" } }),
  utilityPreset({ id: "gis-device-points", category: "gis", zh: "设备点位地图", en: "Asset point map", descriptionZh: "按经纬度展示设备位置和状态", type: "map", key: "gis.devices", previewFamily: "gis", frame: { width: 560, height: 340 }, widget: { map: { mode: "scatter", longitudeField: "longitude", latitudeField: "latitude", valueField: "status" }, linkageParameterKey: "filter.asset" } }),
  utilityPreset({ id: "gis-alarm-heat", category: "gis", zh: "告警热力地图", en: "Alarm heat map", descriptionZh: "按告警密度形成空间热力层", type: "map", key: "gis.alarmHeat", previewFamily: "gis", frame: { width: 560, height: 340 }, widget: { map: { mode: "heat", longitudeField: "longitude", latitudeField: "latitude", valueField: "count" } } }),
  utilityPreset({ id: "gis-logistics-route", category: "gis", zh: "物流路线地图", en: "Logistics route map", descriptionZh: "展示车辆和 AGV 的线路与里程", type: "map", key: "gis.routes", previewFamily: "gis", frame: { width: 560, height: 340 }, widget: { map: { mode: "route", longitudeField: "longitude", latitudeField: "latitude", valueField: "distance" } } }),

  utilityPreset({ id: "topology-process-flow", category: "topology", zh: "工艺流程拓扑", en: "Process topology", descriptionZh: "绑定现有拓扑展示工序和物流连接", type: "topology", key: "topology.process", previewFamily: "topology", frame: { width: 620, height: 360 } }),
  utilityPreset({ id: "topology-energy-network", category: "topology", zh: "能源管网拓扑", en: "Energy network", descriptionZh: "展示电、水、气和蒸汽设备网络", type: "topology", key: "topology.energy", previewFamily: "topology", frame: { width: 620, height: 360 } }),
  utilityPreset({ id: "topology-device-chain", category: "topology", zh: "设备联锁拓扑", en: "Interlock topology", descriptionZh: "查看设备上下游联锁和运行状态", type: "topology", key: "topology.interlock", previewFamily: "topology", frame: { width: 620, height: 360 } }),
  utilityPreset({ id: "topology-communication", category: "topology", zh: "通信网络拓扑", en: "Communication network", descriptionZh: "展示网关、控制器和终端通信关系", type: "topology", key: "topology.communication", previewFamily: "topology", frame: { width: 620, height: 360 } }),

  utilityPreset({ id: "industrial-plc-state", category: "industrial", zh: "控制器运行状态", en: "Controller state", descriptionZh: "显示运行、停止、故障和编程模式", type: "status", key: "industrial.controllerState", previewFamily: "industrial", widget: { field: "state", conditionalRules: [{ id: "controller-fault", operator: "eq", value: "故障", color: "#ff8170", animation: "pulse" }] } }),
  utilityPreset({ id: "industrial-motor-load", category: "industrial", zh: "电机负载仪表", en: "Motor load", descriptionZh: "显示电机当前负载与过载区间", type: "gauge", key: "industrial.motorLoad", previewFamily: "industrial", widget: { field: "load", unit: "%", min: 0, max: 120, conditionalRules: [{ id: "motor-overload", operator: "gt", value: 100, color: "#ff8170" }] } }),
  utilityPreset({ id: "industrial-valve-opening", category: "industrial", zh: "阀门开度", en: "Valve opening", descriptionZh: "表达调节阀实时开度和目标位置", type: "progress", key: "industrial.valveOpening", previewFamily: "industrial", widget: { field: "opening", unit: "%", min: 0, max: 100 } }),
  utilityPreset({ id: "industrial-conveyor-speed", category: "industrial", zh: "输送线速度", en: "Conveyor speed", descriptionZh: "显示传送带当前线速度与设定值", type: "value", key: "industrial.conveyorSpeed", previewFamily: "industrial", widget: { field: "speed", unit: "m/s" } }),
  utilityPreset({ id: "industrial-robot-cycle", category: "industrial", zh: "机器人循环节拍", en: "Robot cycle", descriptionZh: "显示机器人当前任务循环时间", type: "digital-flip", key: "industrial.robotCycle", previewFamily: "industrial", widget: { field: "cycleTime", unit: "s", fontSize: 40 } }),
  utilityPreset({ id: "industrial-safety-gate", category: "industrial", zh: "安全门状态", en: "Safety gate state", descriptionZh: "显示安全门开闭与联锁有效状态", type: "status", key: "industrial.safetyGate", previewFamily: "industrial", widget: { field: "closed", conditionalRules: [{ id: "gate-open", operator: "eq", value: false, color: "#ff8170", animation: "pulse" }] } }),
] as const;
