import type { DashboardComponentPreset } from "./dashboardComponentPresetTypes";
import { analysisPreset } from "./dashboardComponentPresetFactory";

/**
 * 分析预设第二批:堆叠、多系列、双轴、桑基与滚动榜单等进阶图表。
 * 词云/箱线/瀑布/极坐标自 2026-09-12 起为运行时真实图表类型,不再是近似映射。
 */
export const DASHBOARD_ANALYSIS_PRESETS_2: readonly DashboardComponentPreset[] = [
  analysisPreset("stacked-trend-area", "分厂堆叠趋势面积", "Stacked trend area", "按车间堆叠观察产量随时间的构成变化", "area", "production.stackedTrend", "date", "output", { analysis: { dimensionField: "date", seriesField: "workshop", measureField: "output", aggregation: "sum" }, chart: { stacked: true, showLegend: true } }),
  analysisPreset("grouped-series-bar", "产线构成极坐标柱", "Line mix polar bars", "类目环形分布,多系列堆叠对比各产线产品构成", "polarBar", "output.seriesBar", "line", "output", { analysis: { dimensionField: "line", seriesField: "product", measureField: "output", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("keyword-frequency-rank", "反馈关键词词云", "Feedback keyword cloud", "字号随出现频次放大,高频反馈问题一眼可辨", "wordcloud", "feedback.keywords", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 40 } }),
  analysisPreset("cost-treemap-drill", "成本矩形树图钻取", "Cost treemap drill", "面积表达成本中心支出并逐级下钻", "treemap", "cost.treemap", "costCenter", "cost", { analysis: { dimensionField: "costCenter", measureField: "cost", aggregation: "sum", drillFields: ["costCenter", "department", "expenseItem"] } }),
  analysisPreset("line-efficiency-radar", "产线能效雷达对比", "Line efficiency radar", "多产线对比能耗、产能、质量等维度", "radar", "efficiency.radar", "dimension", "score", { analysis: { dimensionField: "dimension", seriesField: "line", measureField: "score", aggregation: "average" }, chart: { showLegend: true } }),
  analysisPreset("alarm-flow-sankey", "告警传播桑基", "Alarm propagation Sankey", "追踪告警从源头到受影响系统的路径", "sankey", "alarm.flow", "source", "count", { analysis: { dimensionField: "source", seriesField: "affected", measureField: "count", aggregation: "sum", sort: "value-desc", limit: 8 } }),
  analysisPreset("alarm-impact-graph", "告警影响关系图", "Alarm impact graph", "节点大小表达影响面,定位传播枢纽", "graph", "alarm.impact", "source", "impact", { analysis: { dimensionField: "source", seriesField: "target", measureField: "impact", aggregation: "sum" } }),
  analysisPreset("hourly-load-distribution", "时段负荷分布", "Hourly load distribution", "按小时聚合展示负荷高低峰时段", "bar", "load.hourly", "hour", "load", { analysis: { dimensionField: "hour", measureField: "load", aggregation: "average" }, chart: { showDataLabels: true } }),
  analysisPreset("tolerance-limit-line", "工序公差箱线分布", "Process tolerance boxplot", "按批次聚合实测尺寸分布,箱体表达四分位与上下须", "boxplot", "quality.tolerance", "batch", "value", { analysis: { dimensionField: "batch", measureField: "value", aggregation: "none" } }),
  analysisPreset("cumulative-transfer-combo", "库存结转瀑布", "Inventory carryover waterfall", "首项为期初结余,逐期展示出入库净变化与累计路径", "waterfall", "inventory.transfer", "date", "quantity", { analysis: { dimensionField: "date", measureField: "quantity", aggregation: "sum" } }),
  analysisPreset("quality-dual-axis-combo", "质量双轴组合", "Quality dual-axis combo", "柱形表达检验数量,折线表达合格率", "combo", "quality.combo", "date", "count", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "count", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["合格率"] } }),
  analysisPreset("rolling-score-table", "滚动绩效榜单", "Rolling score table", "自动滚动的产线绩效榜单与得分", "scroll-table", "report.rollingScore", "line", "score", { field: "score", analysis: { dimensionField: "line", measureField: "score", aggregation: "average", sort: "value-desc", limit: 10 }, report: { mode: "detail", pageSize: 8 } }),
  analysisPreset("region-output-bubble-map", "区域产值气泡地图", "Regional output bubbles", "气泡大小表达各区域产值并联动筛选", "map", "region.output", "region", "output", { linkageParameterKey: "filter.region", map: { mode: "scatter", longitudeField: "longitude", latitudeField: "latitude", valueField: "output" } }),
  analysisPreset("environment-comfort-gauge", "环境舒适度仪表", "Environment comfort gauge", "综合温湿度与空气质量展示舒适指数", "gauge", "environment.comfort", "zone", "comfort", { analysis: { dimensionField: "zone", measureField: "comfort", aggregation: "average" }, min: 0, max: 100 }),

  // 双轴组合深度变体:柱表达量值、线表达比率或另一量纲,secondaryAxisSeries 指定右轴系列。
  analysisPreset("cost-revenue-combo", "成本收入双轴组合", "Cost revenue combo", "柱形表达成本,折线表达收入与利润率", "combo", "business.costRevenue", "month", "amount", { analysis: { dimensionField: "month", seriesField: "metric", measureField: "amount", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["利润率"] } }),
  analysisPreset("energy-output-combo", "能耗产量双轴组合", "Energy output combo", "柱形表达能耗,折线表达同期产量", "combo", "production.energyOutput", "date", "value", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "value", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["产量"] } }),
  analysisPreset("workforce-shift-combo", "人力工时组合分析", "Workforce hours combo", "柱形表达工时投入,折线表达人均产出", "combo", "workforce.hours", "date", "hours", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "hours", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["人均产出"] } }),
  analysisPreset("maintenance-ticket-combo", "维护工单组合", "Maintenance ticket combo", "柱形表达新增工单,折线表达完成率", "combo", "maintenance.tickets", "week", "count", { analysis: { dimensionField: "week", seriesField: "metric", measureField: "count", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["完成率"] } }),
  analysisPreset("discharge-quality-combo", "排放水质双轴组合", "Discharge quality combo", "柱形表达排放量,折线表达合格率", "combo", "environment.discharge", "date", "volume", { analysis: { dimensionField: "date", seriesField: "metric", measureField: "volume", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["合格率"] } }),

  // 同环比复合族:本期量值与同比/环比增长率同图对照。
  analysisPreset("sales-yoy-combo", "销售额同比复合", "Sales YoY combo", "柱形表达销售额,折线表达同比增速", "combo", "business.salesYoy", "month", "amount", { analysis: { dimensionField: "month", seriesField: "metric", measureField: "amount", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["同比"] } }),
  analysisPreset("output-mom-line", "产量环比双线", "Output MoM lines", "本期与上期产量双线对照观察环比", "line", "production.momTrend", "date", "output", { analysis: { dimensionField: "date", seriesField: "period", measureField: "output", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("energy-yoy-area", "能耗同比面积", "Energy YoY area", "本年度与上年度能耗面积叠加对照", "area", "energy.yoyTrend", "month", "consumption", { analysis: { dimensionField: "month", seriesField: "year", measureField: "consumption", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("order-yoy-combo", "订单量同比复合", "Order YoY combo", "柱形表达订单量,折线表达同比增速", "combo", "order.yoyTrend", "month", "count", { analysis: { dimensionField: "month", seriesField: "metric", measureField: "count", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["同比"] } }),
  analysisPreset("profit-mom-combo", "利润环比复合", "Profit MoM combo", "柱形表达利润,折线表达环比增速", "combo", "business.profitMomTrend", "month", "amount", { analysis: { dimensionField: "month", seriesField: "metric", measureField: "amount", aggregation: "sum" }, chart: { showLegend: true, secondaryAxisSeries: ["环比"] } }),

  // ── 词云族(真实 wordcloud):字号随词频放大,高频词一眼可辨 ────────────
  analysisPreset("fault-term-wordcloud", "故障词频词云", "Fault term cloud", "工单故障描述关键词字号随频次放大", "wordcloud", "ops.faultTerms", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 40 } }),
  analysisPreset("sentiment-tag-wordcloud", "舆情标签词云", "Sentiment tag cloud", "舆情标签按提及量分色渲染词云", "wordcloud", "pr.sentimentTags", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", seriesField: "sentiment", measureField: "count", aggregation: "count", sort: "value-desc", limit: 45 } }),
  analysisPreset("customer-voice-wordcloud", "客户呼声词云", "Customer voice cloud", "客服记录高频诉求词聚合展示", "wordcloud", "voc.customerVoice", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 40 } }),
  analysisPreset("hazard-term-wordcloud", "安全隐患词云", "Hazard term cloud", "隐患上报关键词字号随频次放大", "wordcloud", "safety.hazardTerms", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 36 } }),
  analysisPreset("process-term-wordcloud", "工艺术语词云", "Process term cloud", "工艺记录高频术语聚合辅助知识沉淀", "wordcloud", "process.termCloud", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 40 } }),
  analysisPreset("energy-issue-wordcloud", "能耗关注词云", "Energy issue cloud", "能耗异常讨论关键词聚合定位关注点", "wordcloud", "energy.issueCloud", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", measureField: "count", aggregation: "count", sort: "value-desc", limit: 36 } }),
  analysisPreset("review-word-wordcloud", "服务评价词云", "Review word cloud", "服务评价高频词按好评差评分色", "wordcloud", "service.reviewWords", "keyword", "count", { field: "count", analysis: { dimensionField: "keyword", seriesField: "rating", measureField: "count", aggregation: "count", sort: "value-desc", limit: 45 } }),

  // ── 箱线族(真实 boxplot):箱体表达四分位与上下须,定位分布与离群 ──────
  analysisPreset("energy-spread-boxplot", "能耗分布箱线", "Energy spread boxplot", "按车间聚合班次电耗分布对比能耗离散度", "boxplot", "energy.distribution", "workshop", "consumption", { analysis: { dimensionField: "workshop", measureField: "consumption", aggregation: "none" } }),
  analysisPreset("batch-quality-boxplot", "批次质量箱线", "Batch quality boxplot", "按批次聚合纯度检验值分布", "boxplot", "quality.batchPurity", "batch", "purity", { analysis: { dimensionField: "batch", measureField: "purity", aggregation: "none" } }),
  analysisPreset("response-time-boxplot", "响应时长箱线", "Response time boxplot", "按团队聚合工单响应时长分布", "boxplot", "ops.responseBox", "team", "minutes", { analysis: { dimensionField: "team", measureField: "minutes", aggregation: "none" } }),
  analysisPreset("furnace-temp-boxplot", "炉温波动箱线", "Furnace temp boxplot", "按炉号聚合炉温采样分布观察波动", "boxplot", "process.furnaceBox", "furnace", "temperature", { analysis: { dimensionField: "furnace", measureField: "temperature", aggregation: "none" } }),
  analysisPreset("lead-time-boxplot", "交付周期箱线", "Lead time boxplot", "按产品线聚合交付周期分布", "boxplot", "delivery.leadBox", "productLine", "days", { analysis: { dimensionField: "productLine", measureField: "days", aggregation: "none" } }),
  analysisPreset("cleanroom-particle-boxplot", "洁净室粒子箱线", "Cleanroom particle boxplot", "按洁净室聚合粒子浓度分布", "boxplot", "semi.particleBox", "room", "particles", { analysis: { dimensionField: "room", measureField: "particles", aggregation: "none" } }),
  analysisPreset("pump-efficiency-boxplot", "泵效分布箱线", "Pump efficiency boxplot", "按泵组聚合运行效率分布定位劣化", "boxplot", "water.pumpBox", "pump", "efficiency", { analysis: { dimensionField: "pump", measureField: "efficiency", aggregation: "none" } }),
  analysisPreset("outpatient-wait-boxplot", "门诊等待箱线", "Outpatient wait boxplot", "按科室聚合候诊时长分布", "boxplot", "hospital.waitBox", "department", "minutes", { analysis: { dimensionField: "department", measureField: "minutes", aggregation: "none" } }),

  // ── 瀑布族(真实 waterfall):首项基期量、其后逐项增减,累计路径清晰 ────
  analysisPreset("cost-breakdown-waterfall", "成本构成瀑布", "Cost breakdown waterfall", "从材料基期逐项累加人工与制造费用至总成本", "waterfall", "finance.costBreakdown", "item", "amount", { analysis: { dimensionField: "item", measureField: "amount", aggregation: "sum" } }),
  analysisPreset("budget-execute-waterfall", "预算执行瀑布", "Budget execution waterfall", "预算基期按科目执行增减推演期末结余", "waterfall", "finance.budgetWaterfall", "subject", "variance", { analysis: { dimensionField: "subject", measureField: "variance", aggregation: "sum" } }),
  analysisPreset("energy-carry-waterfall", "能耗结转瀑布", "Energy carryover waterfall", "逐月能耗增减推演累计能耗路径", "waterfall", "energy.carryover", "month", "delta", { analysis: { dimensionField: "month", measureField: "delta", aggregation: "sum" } }),
  analysisPreset("gross-profit-waterfall", "毛利变动瀑布", "Gross profit bridge", "从价、量、成本三因素拆解毛利变化", "waterfall", "finance.gpBridge", "driver", "delta", { analysis: { dimensionField: "driver", measureField: "delta", aggregation: "sum" } }),
  analysisPreset("spare-consume-waterfall", "备件消耗瀑布", "Spare consumption waterfall", "逐月备件出入库净变化与累计路径", "waterfall", "spare.consumption", "month", "netChange", { analysis: { dimensionField: "month", measureField: "netChange", aggregation: "sum" } }),
  analysisPreset("capacity-loss-waterfall", "产能损失瀑布", "Capacity loss waterfall", "计划产能扣除停机换型质量损失得有效产能", "waterfall", "capacity.lossBridge", "lossFactor", "hours", { analysis: { dimensionField: "lossFactor", measureField: "hours", aggregation: "sum" } }),
  analysisPreset("nrw-bridge-waterfall", "产销差分解瀑布", "NRW bridge waterfall", "供水量扣除漏损计量与免费用水得售水量", "waterfall", "water.nrwBridge", "segment", "volume", { analysis: { dimensionField: "segment", measureField: "volume", aggregation: "sum" } }),

  // ── 极坐标族(真实 polarBar):类目环布,多系列环形堆叠 ──────────────────
  analysisPreset("time-share-polar", "时段占比极坐标", "Hourly share polar", "24 小时环布对比各时段负荷占比", "polarBar", "load.hourlyPolar", "hour", "share", { analysis: { dimensionField: "hour", measureField: "share", aggregation: "average" } }),
  analysisPreset("defect-mix-polar", "废品构成极坐标", "Defect mix polar", "环形堆叠对比各产线废品类型构成", "polarBar", "quality.defectPolar", "defectType", "count", { analysis: { dimensionField: "defectType", seriesField: "line", measureField: "count", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("energy-mix-polar", "能耗构成极坐标", "Energy mix polar", "电汽水气各类能源占比环形分布", "polarBar", "energy.mixPolar", "energyType", "consumption", { analysis: { dimensionField: "energyType", measureField: "consumption", aggregation: "sum" } }),
  analysisPreset("shift-output-polar", "班次产出极坐标", "Shift output polar", "班次环布堆叠对比各产线产出", "polarBar", "production.shiftPolar", "shift", "output", { analysis: { dimensionField: "shift", seriesField: "line", measureField: "output", aggregation: "sum" }, chart: { showLegend: true } }),
  analysisPreset("fault-hour-polar", "故障时段极坐标", "Fault hour polar", "24 小时环布统计故障高发时段", "polarBar", "alarm.hourlyPolar", "hour", "count", { analysis: { dimensionField: "hour", measureField: "count", aggregation: "sum" } }),
  analysisPreset("arrival-slot-polar", "到货时段极坐标", "Arrival slot polar", "到货时段环形分布辅助月台排班", "polarBar", "logistics.arrivalPolar", "slot", "truckloads", { analysis: { dimensionField: "slot", measureField: "truckloads", aggregation: "sum" } }),
  analysisPreset("pollutant-mix-polar", "污染物构成极坐标", "Pollutant mix polar", "各污染物排放量环形分布", "polarBar", "environment.pollutantPolar", "pollutant", "emission", { analysis: { dimensionField: "pollutant", measureField: "emission", aggregation: "sum" } }),
  analysisPreset("service-window-polar", "窗口业务极坐标", "Window business polar", "窗口业务类型环形分布辅助排班", "polarBar", "gov.windowPolar", "category", "cases", { analysis: { dimensionField: "category", measureField: "cases", aggregation: "sum" } }),
] as const;
