import type { DashboardComponentPreset } from "./dashboardComponentPresetTypes";
import { reportPreset } from "./dashboardComponentPresetFactory";

/** 报表预设第二批:小计/合计、条件格式、分页与冻结首列等经营报表常用形态。 */
export const DASHBOARD_REPORT_PRESETS_2: readonly DashboardComponentPreset[] = [
  reportPreset("group-subtotal-report", "分组小计表", "Grouped subtotal report", "按车间分组汇总并逐组显示小计", "table", "report.groupSubtotal", { analysis: { dimensionField: "workshop", measureField: "value", aggregation: "sum" }, report: { mode: "grouped", rowField: "workshop", valueFields: ["plan", "actual"], aggregation: "sum", showSubtotal: true, showGrandTotal: true, stripedRows: true } }),
  reportPreset("sales-crosstab-report", "区域品类交叉表", "Sales crosstab report", "按区域和品类交叉汇总销售额", "table", "report.salesCrosstab", { analysis: { dimensionField: "region", seriesField: "category", measureField: "amount", aggregation: "sum" }, report: { mode: "crosstab", rowField: "region", columnField: "category", valueField: "amount", aggregation: "sum", showSubtotal: true, showGrandTotal: true, valueFormat: "number", decimalPlaces: 2 } }),
  reportPreset("project-progress-report", "项目进度汇总表", "Project progress report", "按项目汇总计划、实绩与偏差", "table", "report.projectProgress", { report: { mode: "grouped", rowField: "project", valueFields: ["plan", "actual", "deviation"], aggregation: "sum", showGrandTotal: true, stripedRows: true }, conditionalRules: [{ id: "deviation-over", field: "deviation", operator: "gt", value: 0, color: "#ff9b73" }] }),
  reportPreset("detail-total-report", "明细合计表", "Detail with totals", "明细行与合计行同屏对照数量金额", "table", "report.detailTotal", { report: { mode: "detail", pageSize: 15, showRowNumbers: true, stripedRows: true, showGrandTotal: true } }),
  reportPreset("conditional-format-report", "条件格式明细表", "Conditional formatting report", "按数值区间自动着色与加粗关键行", "table", "report.conditionalFormat", { report: { mode: "detail", pageSize: 12, showRowNumbers: true, stripedRows: true }, conditionalRules: [{ id: "stock-warning", field: "stock", operator: "lt", value: 50, color: "#ff8170", fontWeight: 700 }, { id: "stock-normal", field: "stock", operator: "between", value: 50, valueTo: 200, backgroundColor: "#2b4a44" }, { id: "stock-critical", field: "stock", operator: "gt", value: 200, color: "#e8bd68" }] }),
  reportPreset("paged-inventory-report", "分页库存明细表", "Paged inventory report", "每页 20 条浏览库存并冻结首列", "table", "report.pagedInventory", { report: { mode: "detail", pageSize: 20, showRowNumbers: true, stripedRows: true, freezeFirstColumn: true } }),
  reportPreset("wide-freeze-report", "宽表冻结首列", "Wide freeze-column report", "横向浏览多列指标时首列保持可见", "table", "report.wideFreeze", { report: { mode: "detail", pageSize: 10, showRowNumbers: true, freezeFirstColumn: true, stripedRows: true } }),
  reportPreset("line-kpi-summary-report", "产线 KPI 汇总表", "Line KPI summary report", "按产线汇总产量、合格与停机数据", "table", "report.lineKpi", { report: { mode: "grouped", rowField: "line", valueFields: ["output", "qualified", "downtime"], aggregation: "sum", showGrandTotal: true, valueFormat: "number", decimalPlaces: 1 } }),

  // 交叉表变体族(波次 F):换业务维度与数值格式,而非重复同一张表。
  reportPreset("brand-region-crosstab-report", "区域品牌交叉表", "Brand region crosstab", "区域与品牌交叉汇总销售额并显示总计", "table", "report.brandRegion", { analysis: { dimensionField: "region", seriesField: "brand", measureField: "sales", aggregation: "sum" }, report: { mode: "crosstab", rowField: "region", columnField: "brand", valueField: "sales", aggregation: "sum", showSubtotal: true, showGrandTotal: true, valueFormat: "currency", currency: "¥", decimalPlaces: 0 } }),
  reportPreset("share-percent-crosstab-report", "占比交叉汇总表", "Share percent crosstab", "渠道与品类交叉并以百分比格式呈现结构", "table", "report.sharePercent", { analysis: { dimensionField: "channel", seriesField: "category", measureField: "share", aggregation: "sum" }, report: { mode: "crosstab", rowField: "channel", columnField: "category", valueField: "share", aggregation: "sum", showGrandTotal: true, valueFormat: "percent", decimalPlaces: 1 } }),
  // 树形明细变体:三级层级钻取台账,组织树承载集团-部门-班组工时。
  reportPreset("ledger-tree-detail-report", "组织树台账明细表", "Org ledger tree report", "集团-部门-班组三级分组展开工时台账", "table", "report.orgLedgerTree", { analysis: { dimensionField: "division", measureField: "hours", aggregation: "sum", drillFields: ["division", "department", "team"] }, report: { mode: "grouped", rowField: "division", valueFields: ["hours", "headcount"], aggregation: "sum", showSubtotal: true, showGrandTotal: true, stripedRows: true } }),
  // 期间汇总变体:按月区间收入支出结余三列对照。
  reportPreset("period-range-summary-report", "月度区间汇总表", "Period range summary", "按月汇总收入支出结余并染色负结余", "table", "report.periodRange", { report: { mode: "grouped", rowField: "month", valueFields: ["income", "expense", "balance"], aggregation: "sum", showGrandTotal: true, stripedRows: true, valueFormat: "number", decimalPlaces: 1 }, conditionalRules: [{ id: "balance-negative", field: "balance", operator: "lt", value: 0, color: "#ff8170", fontWeight: 700 }] }),
] as const;
