import type { DashboardComponentPreset } from "./dashboardComponentPresetTypes";
import { reportPreset } from "./dashboardComponentPresetFactory";

export const DASHBOARD_REPORT_PRESETS: readonly DashboardComponentPreset[] = [
  reportPreset("crosstab-report", "交叉分析表", "Crosstab report", "按区域和品类交叉汇总并显示总计", "table", "report.crosstab", { analysis: { dimensionField: "region", seriesField: "category", measureField: "amount", aggregation: "sum" }, report: { mode: "crosstab", rowField: "region", columnField: "category", valueField: "amount", aggregation: "sum", pageSize: 12, showGrandTotal: true } }),
  reportPreset("grouped-report", "分组汇总表", "Grouped report", "按业务分组汇总指标并显示总计", "table", "report.grouped", { analysis: { dimensionField: "group", measureField: "value", aggregation: "sum" }, report: { mode: "grouped", rowField: "group", valueField: "value", aggregation: "sum", pageSize: 10, showGrandTotal: true } }),
  reportPreset("rolling-alarm-table", "告警滚动表", "Scrolling alarms", "自动滚动展示最新告警与等级", "scroll-table", "alarms", { report: { mode: "detail", pageSize: 6 }, conditionalRules: [{ id: "critical-alarm", field: "level", operator: "contains", value: "高", color: "#ff8170", fontWeight: 700 }] }),
  reportPreset("detail-report", "业务明细报表", "Business details", "分页、行号、斑马纹和冻结首列", "table", "report.details", { report: { mode: "detail", pageSize: 12, showRowNumbers: true, freezeFirstColumn: true, stripedRows: true } }),
  reportPreset("production-shift-report", "班次生产报表", "Shift production report", "按班次汇总计划、实绩和合格数量", "table", "report.shiftProduction", { report: { mode: "grouped", rowField: "shift", valueFields: ["plan", "actual", "qualified"], aggregation: "sum", showGrandTotal: true, stripedRows: true } }),
  reportPreset("energy-crosstab-report", "能源交叉报表", "Energy crosstab", "按车间和能源类型交叉汇总消耗", "table", "report.energy", { report: { mode: "crosstab", rowField: "workshop", columnField: "energyType", valueField: "consumption", aggregation: "sum", showSubtotal: true, showGrandTotal: true, valueFormat: "number", decimalPlaces: 2 } }),
  reportPreset("quality-defect-report", "质量缺陷明细", "Quality defect details", "追溯产品、工位、缺陷和责任批次", "table", "report.qualityDefects", { report: { mode: "detail", pageSize: 15, showRowNumbers: true, freezeFirstColumn: true, stripedRows: true }, conditionalRules: [{ id: "critical-defect", field: "severity", operator: "eq", value: "严重", color: "#ff8170", fontWeight: 700 }] }),
  reportPreset("maintenance-orders", "维护工单滚屏", "Maintenance orders", "滚动展示待处理、逾期和执行中工单", "scroll-table", "maintenance.orders", { report: { mode: "detail", pageSize: 7 }, conditionalRules: [{ id: "overdue-order", field: "overdue", operator: "eq", value: true, color: "#ff9b73", animation: "pulse" }] }),
  reportPreset("inventory-shortage-rank", "缺料风险排行", "Shortage risk ranking", "按预计缺料时间排列高风险物料", "rank", "inventory.shortage", { field: "hoursRemaining", analysis: { dimensionField: "material", measureField: "hoursRemaining", aggregation: "minimum", sort: "value-asc", limit: 10 } }),
  reportPreset("downtime-loss-rank", "停机损失排行", "Downtime loss ranking", "按停机分钟和产能损失定位重点设备", "rank", "downtime.loss", { field: "lostMinutes", analysis: { dimensionField: "asset", measureField: "lostMinutes", aggregation: "sum", sort: "value-desc", limit: 12 } }),
  reportPreset("alarm-history-report", "告警历史报表", "Alarm history report", "按时间、来源和处置状态查询历史告警", "table", "report.alarmHistory", { report: { mode: "detail", pageSize: 20, showRowNumbers: true, freezeFirstColumn: true, stripedRows: true }, conditionalRules: [{ id: "unclosed-alarm", field: "closed", operator: "eq", value: false, color: "#ffbd73" }] }),
  reportPreset("carbon-accounting-report", "碳核算分组表", "Carbon accounting", "按组织边界和排放范围汇总碳数据", "table", "report.carbon", { report: { mode: "grouped", rowField: "organization", valueFields: ["scope1", "scope2", "scope3"], aggregation: "sum", showGrandTotal: true, valueFormat: "number", decimalPlaces: 2 } }),
] as const;

