import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { PassThrough, Readable } from "node:stream";
import { afterEach, describe, expect, it, vi } from "vitest";
import { LocalObjectStore } from "./objects.js";
import { capturePublicationResource, storePublicationResourceBytes } from "./publicationResourceSnapshot.js";

const directories: string[] = [];
afterEach(async () => { await Promise.all(directories.splice(0).map(dir => rm(dir, { recursive: true, force: true }))); });
async function fixture() {
  const dataDir = await mkdtemp(path.join(tmpdir(), "publication-resource-")); directories.push(dataDir);
  const sourceKey = "projects/project/models/中文 文件.bin", content = Buffer.from([0, 1, 128, 255]);
  await mkdir(path.dirname(path.join(dataDir, sourceKey)), { recursive: true }); await writeFile(path.join(dataDir, sourceKey), content);
  const objects = new LocalObjectStore(dataDir);
  const input = { objects, dataDir, sourceKey, projectId: "project" };
  const sha256 = createHash("sha256").update(content).digest("hex");
  const key = `projects/project/publication-resources/sha256/${sha256}`;
  const clean = async () => expect(await readdir(path.join(dataDir, ".publication-resource-staging"))).toEqual([]);
  return { input, content, sha256, key, clean };
}
describe("publication resource snapshots", () => {
  it("stores generated bytes privately with the same content identity and snapshots caller memory", async () => {
    const { input, content, sha256, key, clean } = await fixture();
    const original = Buffer.from(content);
    const pending = storePublicationResourceBytes(input, content);
    content.fill(99);
    expect(await pending).toEqual({ key, bytes: original.length, sha256 });
    expect(await readFile(path.join(input.dataDir, key))).toEqual(original);
    await expect(readdir(path.join(input.dataDir, "projects/project/generated"))).rejects.toMatchObject({ code: "ENOENT" });
    await clean();
  });
  it("applies generated-resource budgets, cancellation and expected hashes before persistence", async () => {
    const { input, content } = await fixture();
    const put = vi.spyOn(input.objects, "putFileIfMissing");
    await expect(storePublicationResourceBytes({ ...input, maxBytes: 2 }, content)).rejects.toThrow("上限");
    await expect(storePublicationResourceBytes({ ...input, signal: AbortSignal.abort() }, content)).rejects.toMatchObject({ name: "AbortError" });
    await expect(storePublicationResourceBytes({ ...input, expected: { bytes: content.length, sha256: "0".repeat(64) } }, content)).rejects.toThrow("不匹配");
    expect(put).not.toHaveBeenCalled();
  });
  it("captures real local bytes without modifying the source and supports concurrent same-content capture", async () => {
    const { input, content, sha256, key, clean } = await fixture();
    const results = await Promise.all([capturePublicationResource(input), capturePublicationResource(input)]);
    expect(results).toEqual([{ key, bytes: content.length, sha256 }, { key, bytes: content.length, sha256 }]);
    expect(await readFile(path.join(input.dataDir, key))).toEqual(content);
    expect(await readFile(path.join(input.dataDir, input.sourceKey))).toEqual(content); await clean();
  });
  it.each(["projects/foreign/a", "https://example.test/a", "projects/project/../a", "projects/project//a", "projects/project/./a", "projects/project/a\\b", "projects/project/C:a", "projects/project/%2e%2e/a", "projects/project/a.", "projects/project/NUL"])("rejects unsafe source %s before reading", async sourceKey => {
    const { input } = await fixture(); const read = vi.spyOn(input.objects, "read");
    await expect(capturePublicationResource({ ...input, sourceKey })).rejects.toThrow(/路径/); expect(read).not.toHaveBeenCalled();
  });
  it("enforces streamed size and expected hash and cleans failed staging", async () => {
    const { input, clean } = await fixture();
    await expect(capturePublicationResource({ ...input, maxBytes: 3 })).rejects.toThrow(/上限/); await clean();
    await expect(capturePublicationResource({ ...input, expected: { bytes: 4, sha256: "0".repeat(64) } })).rejects.toThrow(/不匹配/); await clean();
  });
  it("rejects a corrupted existing content key without overwriting it", async () => {
    const { input, key, clean } = await fixture(); await mkdir(path.dirname(path.join(input.dataDir, key)), { recursive: true });
    await writeFile(path.join(input.dataDir, key), "corrupt");
    await expect(capturePublicationResource(input)).rejects.toThrow(/不匹配/);
    expect(await readFile(path.join(input.dataDir, key), "utf8")).toBe("corrupt"); await clean();
  });
  it("requires completed success even after all stream bytes arrive", async () => {
    const { input, content, clean } = await fixture();
    vi.spyOn(input.objects, "read").mockImplementation(async () => ({ stream: Readable.from([content]), completed: Promise.reject(new Error("mc failed")) }));
    const put = vi.spyOn(input.objects, "putFileIfMissing");
    await expect(capturePublicationResource(input)).rejects.toThrow(/mc failed|Premature close/);
    expect(put).not.toHaveBeenCalled(); await clean();
  });
  it("validates actual remote bytes after upload instead of trusting successful put", async () => {
    const { input, content, clean } = await fixture(); let reads = 0;
    vi.spyOn(input.objects, "read").mockImplementation(async () => ({ stream: Readable.from([reads++ ? Buffer.from("evil") : content]), completed: Promise.resolve() }));
    const put = vi.spyOn(input.objects, "putFileIfMissing");
    await expect(capturePublicationResource(input)).rejects.toThrow(/不匹配/); expect(put).toHaveBeenCalledOnce(); await clean();
  });
  it("cancels a live resource stream and cleans staging", async () => {
    const { input, clean } = await fixture(); const controller = new AbortController(), stream = new PassThrough();
    vi.spyOn(input.objects, "read").mockResolvedValue({ stream, completed: new Promise(() => {}) });
    const pending = capturePublicationResource({ ...input, signal: controller.signal });
    const rejected = expect(pending).rejects.toMatchObject({ name: "AbortError" });
    await vi.waitFor(() => expect(stream.listenerCount("data")).toBeGreaterThan(0));
    stream.write(Buffer.from("part")); controller.abort(); await rejected;
    expect(stream.destroyed).toBe(true); await clean();
  });
  it("rejects pre-cancellation without reading", async () => {
    const { input } = await fixture(); const controller = new AbortController(); controller.abort();
    const read = vi.spyOn(input.objects, "read");
    await expect(capturePublicationResource({ ...input, signal: controller.signal })).rejects.toMatchObject({ name: "AbortError" });
    expect(read).not.toHaveBeenCalled();
  });

  it("rejects a source traversing a real directory junction without reading outside bytes", async () => {
    const { input, clean } = await fixture();
    const outside = await mkdtemp(path.join(tmpdir(), "publication-outside-")); directories.push(outside);
    await writeFile(path.join(outside, "secret.bin"), "outside");
    await symlink(outside, path.join(input.dataDir, "projects/project/escape"), "junction");
    const read = vi.spyOn(input.objects, "read");
    await expect(capturePublicationResource({ ...input, sourceKey: "projects/project/escape/secret.bin" })).rejects.toThrow(/符号链接/);
    expect(read).not.toHaveBeenCalled(); await clean();
  });

  it("rejects a source file symlink when supported by the host", async context => {
    const { input, clean } = await fixture(); const target = path.join(input.dataDir, "outside.bin");
    await writeFile(target, "outside");
    try { await symlink(target, path.join(input.dataDir, "projects/project/link.bin"), "file"); }
    catch (reason) {
      if (["EPERM", "EACCES"].includes((reason as NodeJS.ErrnoException).code ?? "")) {
        context.skip("Host does not permit file symlinks"); return;
      }
      throw reason;
    }
    await expect(capturePublicationResource({ ...input, sourceKey: "projects/project/link.bin" })).rejects.toThrow(/符号链接/); await clean();
  });

  it("captures a genuinely empty resource with zero budget and its empty SHA", async () => {
    const { input, clean } = await fixture(); await writeFile(path.join(input.dataDir, input.sourceKey), "");
    const sha256 = createHash("sha256").update("").digest("hex");
    expect(await capturePublicationResource({ ...input, maxBytes: 0, expected: { bytes: 0, sha256 } })).toMatchObject({ bytes: 0, sha256 });
    await clean();
  });

  it.each([-1, NaN, Infinity, 1.5, Number.MAX_SAFE_INTEGER + 1])("rejects invalid budget %s before source access", async maxBytes => {
    const { input } = await fixture(); const read = vi.spyOn(input.objects, "read");
    await expect(capturePublicationResource({ ...input, maxBytes })).rejects.toThrow(/上限无效/); expect(read).not.toHaveBeenCalled();
  });

  it("cleans staging when the source is missing without creating its directories", async () => {
    const { input, clean } = await fixture();
    await expect(capturePublicationResource({ ...input, sourceKey: "projects/project/missing/file.bin" })).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readdir(path.join(input.dataDir, "projects/project"))).not.toContain("missing"); await clean();
  });

  it("cleans staging when upload rejects and retains the original source", async () => {
    const { input, clean, content } = await fixture();
    vi.spyOn(input.objects, "putFileIfMissing").mockRejectedValue(new Error("upload unavailable"));
    await expect(capturePublicationResource(input)).rejects.toThrow("upload unavailable");
    expect(await readFile(path.join(input.dataDir, input.sourceKey))).toEqual(content); await clean();
  });

  it("waits for in-flight upload to settle before cleaning and rejecting late cancellation", async () => {
    const { input, clean } = await fixture(); const controller = new AbortController();
    let entered!: () => void, release!: () => void;
    const uploading = new Promise<void>(resolve => { entered = resolve; });
    const completed = new Promise<void>(resolve => { release = resolve; });
    vi.spyOn(input.objects, "putFileIfMissing").mockImplementation(async () => { entered(); await completed; });
    const read = vi.spyOn(input.objects, "read");
    let settled = false;
    const pending = capturePublicationResource({ ...input, signal: controller.signal });
    void pending.then(() => { settled = true; }, () => { settled = true; });
    const rejection = expect(pending).rejects.toMatchObject({ name: "AbortError" });
    await uploading; controller.abort(); await Promise.resolve(); expect(settled).toBe(false);
    expect(await readdir(path.join(input.dataDir, ".publication-resource-staging"))).toHaveLength(1);
    release(); await rejection; expect(read).toHaveBeenCalledOnce(); await clean();
  });
});
