import { DEEP_STANDARD_LIGHTING_LAYOUT_V1 } from "./surface.js";
import type { ShaderStageOutput } from "./types.js";

const declarations = [
  "struct DeepPbrFrame {",
  "  view: mat4x4f,",
  "  light: mat4x4f,",
  "  eye: vec4f,",
  "  background: vec4f,",
  "  floor: vec4f,",
  "  lightDirection: vec4f,",
  "  tuning: vec4f,",
  "};",
  "@group(0) @binding(0) var<uniform> deepPbrFrame: DeepPbrFrame;",
  "@group(0) @binding(1) var deepShadowMap: texture_depth_2d;",
  "@group(0) @binding(2) var deepShadowSampler: sampler_comparison;",
  "@group(0) @binding(3) var deepSpecularEnvironment: texture_cube<f32>;",
  "@group(0) @binding(4) var deepDiffuseEnvironment: texture_cube<f32>;",
  "@group(0) @binding(5) var deepBrdfLut: texture_2d<f32>;",
  "@group(0) @binding(6) var deepEnvironmentSampler: sampler;",
  "const DEEP_PI: f32 = 3.141592653589793;",
  "fn deepSafeNormalize(value: vec3f, fallback: vec3f) -> vec3f {",
  "  let lengthSquared = dot(value, value);",
  "  let normalized = value * inverseSqrt(max(lengthSquared, 0.00000001));",
  "  return select(fallback, normalized, lengthSquared > 0.00000001);",
  "}",
  "fn deepFresnelSchlick(cosine: f32, f0: vec3f) -> vec3f {",
  "  return f0 + (vec3f(1.0) - f0) * pow(1.0 - cosine, 5.0);",
  "}",
  "fn deepDistributionGgx(nDotH: f32, roughness: f32) -> f32 {",
  "  let alpha = roughness * roughness;",
  "  let alpha2 = alpha * alpha;",
  "  let denominator = nDotH * nDotH * (alpha2 - 1.0) + 1.0;",
  "  return alpha2 / max(DEEP_PI * denominator * denominator, 0.000001);",
  "}",
  "fn deepGeometrySchlickGgx(nDotX: f32, roughness: f32) -> f32 {",
  "  let k = (roughness + 1.0) * (roughness + 1.0) / 8.0;",
  "  return nDotX / max(nDotX * (1.0 - k) + k, 0.0001);",
  "}",
  "fn deepShadowVisibility(worldPosition: vec3f, nDotL: f32) -> f32 {",
  "  let clip = deepPbrFrame.light * vec4f(worldPosition, 1.0);",
  "  let projected = clip.xyz / clip.w;",
  "  let uv = projected.xy * vec2f(0.5, -0.5) + 0.5;",
  "  let bias = max(0.00025, 0.001 * (1.0 - nDotL));",
  "  var sampled = 0.0;",
  "  let texel = 3.0 / vec2f(textureDimensions(deepShadowMap));",
  "  for (var y = -1; y <= 1; y++) {",
  "    for (var x = -1; x <= 1; x++) {",
  "      sampled += textureSampleCompareLevel(deepShadowMap, deepShadowSampler, uv + vec2f(f32(x), f32(y)) * texel, projected.z - bias);",
  "    }",
  "  }",
  "  let inside = all(uv >= vec2f(0.0)) && all(uv <= vec2f(1.0)) && projected.z >= 0.0 && projected.z <= 1.0;",
  "  let visible = select(1.0, sampled / 9.0, inside);",
  "  return visible;",
  "}",
  "fn deepLowerStandardPbr(worldPosition: vec3f, baseInput: vec3f, normalInput: vec3f, metallicInput: f32, roughnessInput: f32, occlusionInput: f32, emission: vec3f, alphaInput: f32) -> vec4f {",
  "  let baseColor = max(baseInput, vec3f(0.0));",
  "  let normal = deepSafeNormalize(normalInput, vec3f(0.0, 1.0, 0.0));",
  "  let view = deepSafeNormalize(deepPbrFrame.eye.xyz - worldPosition, vec3f(0.0, 0.0, 1.0));",
  "  let light = deepSafeNormalize(deepPbrFrame.lightDirection.xyz, vec3f(0.0, 1.0, 0.0));",
  "  let halfVector = deepSafeNormalize(view + light, normal);",
  "  let metallic = clamp(metallicInput, 0.0, 1.0);",
  "  let roughness = clamp(roughnessInput, 0.045, 1.0);",
  "  let nDotL = clamp(dot(normal, light), 0.0, 1.0);",
  "  let nDotV = clamp(dot(normal, view), 0.0001, 1.0);",
  "  let nDotH = clamp(dot(normal, halfVector), 0.0, 1.0);",
  "  let vDotH = clamp(dot(view, halfVector), 0.0, 1.0);",
  "  let f0 = mix(vec3f(0.04), baseColor, metallic);",
  "  let fresnel = deepFresnelSchlick(vDotH, f0);",
  "  let distribution = deepDistributionGgx(nDotH, roughness);",
  "  let geometry = deepGeometrySchlickGgx(nDotV, roughness) * deepGeometrySchlickGgx(nDotL, roughness);",
  "  let specular = distribution * geometry * fresnel / max(4.0 * nDotV * nDotL, 0.0001);",
  "  let diffuse = (vec3f(1.0) - fresnel) * (1.0 - metallic) * baseColor / DEEP_PI;",
  "  let shadow = deepShadowVisibility(worldPosition, nDotL);",
  "  let directRadiance = vec3f(2.5, 2.4, 2.25);",
  "  let direct = (diffuse + specular) * directRadiance * nDotL * shadow;",
  "  let occlusion = clamp(occlusionInput, 0.0, 1.0);",
  "  let indirectFresnel = f0 + (max(vec3f(1.0 - roughness), f0) - f0) * pow(1.0 - nDotV, 5.0);",
  "  let irradiance = textureSampleLevel(deepDiffuseEnvironment, deepEnvironmentSampler, normal, 0.0).rgb;",
  "  let indirectDiffuse = (vec3f(1.0) - indirectFresnel) * (1.0 - metallic) * baseColor * irradiance;",
  "  let reflection = reflect(-view, normal);",
  "  let maxSpecularLod = f32(textureNumLevels(deepSpecularEnvironment) - 1u);",
  "  let radiance = textureSampleLevel(deepSpecularEnvironment, deepEnvironmentSampler, reflection, roughness * maxSpecularLod).rgb;",
  "  let dfg = textureSampleLevel(deepBrdfLut, deepEnvironmentSampler, vec2f(nDotV, roughness), 0.0).rg;",
  "  let energyCompensation = vec3f(1.0) + f0 * (1.0 / max(dfg.x + dfg.y, 0.05) - 1.0);",
  "  let indirectSpecular = radiance * (f0 * dfg.x + dfg.y) * energyCompensation;",
  "  let color = direct + (indirectDiffuse + indirectSpecular) * occlusion + emission;",
  "  return vec4f(max(color, vec3f(0.0)), clamp(alphaInput, 0.0, 1.0));",
  "}",
] as const;

export function emitStandardPbrDeclarations(lines: string[]): void {
  lines.push(...declarations);
}

export function standardPbrReturn(output: Extract<ShaderStageOutput, { semantic: "surface" }>): string {
  const node = (field: keyof typeof output.fields): string => `n_${output.fields[field]}`;
  return `deepLowerStandardPbr(input.v_${DEEP_STANDARD_LIGHTING_LAYOUT_V1.worldPositionVarying}, ${node("baseColor")}, ${node("normal")}, ${node("metallic")}, ${node("roughness")}, ${node("occlusion")}, ${node("emission")}, ${node("alpha")})`;
}
